#!/usr/bin/env python3
"""
claude_mem_digest.py - bridge claude-mem's memory into Cowork (and human-readable docs).

WHY THIS EXISTS
---------------
claude-mem (installed 24 Jun 2026) gives the *Claude Code CLI* automatic session-to-session
memory. Cowork (the desktop app) does NOT share that memory - different front-end, no hooks.
But claude-mem writes everything to a local SQLite DB, so this script reads that DB and emits a
SMALL, CAPPED Markdown digest that BOTH Cowork and Claude Code can read cheaply.

KEY DESIGN CHOICE (context-safe): we never dump the raw DB into context. We emit only the last
N session SUMMARIES (Request / Learned / Completed / Next Steps) - a few KB - mirroring
claude-mem's own progressive-disclosure principle. Default N=10; ask for more on demand.

THE DB IS LIVE (WAL mode) - so we copy it to a temp dir and open READ-ONLY before querying,
to avoid the 'disk I/O error' you get opening a worker-held WAL db over the FUSE mount.

USAGE
  python3 claude_mem_digest.py                 # last 10 sessions, all projects -> CLAUDE_MEM_DIGEST.md
  python3 claude_mem_digest.py --limit 25      # last 25 sessions
  python3 claude_mem_digest.py --project MarketSquare
  python3 claude_mem_digest.py --out /path/to/file.md
  python3 claude_mem_digest.py --db /custom/.claude-mem/claude-mem.db

EXIT 0 ok · 1 db not found · 2 read error
"""
import argparse, os, sqlite3, sys, tempfile, shutil, glob
from datetime import datetime


def find_db(explicit):
    if explicit:
        return explicit if os.path.exists(explicit) else None
    # try common locations across OSes / mounts
    candidates = [
        os.path.expanduser("~/.claude-mem/claude-mem.db"),
        "/sessions/*/mnt/.claude-mem/claude-mem.db",
        os.path.expandvars(r"%USERPROFILE%\.claude-mem\claude-mem.db"),
        r"C:\Users\David\.claude-mem\claude-mem.db",
    ]
    for c in candidates:
        if "*" in c:
            hits = glob.glob(c)
            if hits:
                return hits[0]
        elif os.path.exists(c):
            return c
    return None


def open_readonly_snapshot(db_path):
    """Copy db (+wal/+shm) off the live mount into a temp dir, open read-only.
    Avoids disk-I/O errors from the worker's open WAL connection."""
    tmp = tempfile.mkdtemp(prefix="cmdigest_")
    base = os.path.join(tmp, "cm.db")
    shutil.copy2(db_path, base)
    for ext in ("-wal", "-shm"):
        src = db_path + ext
        if os.path.exists(src):
            try:
                shutil.copy2(src, base + ext)
            except OSError:
                pass
    con = sqlite3.connect(f"file:{base}?mode=ro", uri=True)
    return con, tmp


def short(text, cap=600):
    if not text:
        return ""
    text = " ".join(text.split())
    return text if len(text) <= cap else text[:cap].rstrip() + " ..."


def build(con, limit, project):
    cur = con.cursor()
    where, params = "", []
    if project:
        where = "WHERE project = ?"
        params.append(project)
    params.append(limit)
    rows = cur.execute(f"""
        SELECT project, request, learned, completed, next_steps, created_at, investigated
        FROM session_summaries
        {where}
        ORDER BY created_at_epoch DESC
        LIMIT ?
    """, params).fetchall()

    # also a count of observations for context (not dumped, just a number)
    obs_n = cur.execute("SELECT COUNT(*) FROM observations").fetchone()[0]
    total_sessions = cur.execute("SELECT COUNT(*) FROM session_summaries").fetchone()[0]
    return rows, obs_n, total_sessions


def render(rows, obs_n, total_sessions, limit, project):
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    scope = f"project **{project}**" if project else "all projects"
    lines = []
    lines.append("# claude-mem digest")
    lines.append("")
    lines.append(f"> Auto-generated by `claude_mem_digest.py` on {now}. Scope: {scope}.")
    lines.append(f"> Showing the last {len(rows)} of {total_sessions} session summaries "
                 f"({obs_n} raw observations in the store, not shown here).")
    lines.append(f"> This is the capped Cowork-readable view. Need deeper history? "
                 f"re-run with `--limit N` or ask in Cowork.")
    lines.append("")
    if not rows:
        lines.append("_No session summaries captured yet. Work a Claude Code session, then re-run._")
        return "\n".join(lines) + "\n"
    for i, (proj, req, learned, completed, nxt, created, investigated) in enumerate(rows, 1):
        when = (created or "")[:16].replace("T", " ")
        lines.append(f"## {i}. {proj or '(no project)'} — {when}")
        if req:
            lines.append(f"**Request:** {short(req, 300)}")
        if learned:
            lines.append(f"**Learned:** {short(learned)}")
        if completed:
            lines.append(f"**Completed:** {short(completed)}")
        if nxt:
            lines.append(f"**Next steps:** {short(nxt, 400)}")
        lines.append("")
    return "\n".join(lines) + "\n"


def main(argv):
    ap = argparse.ArgumentParser(description="Emit a capped Markdown digest of claude-mem memory.")
    ap.add_argument("--limit", type=int, default=10, help="how many recent sessions (default 10)")
    ap.add_argument("--project", default=None, help="filter to one project (e.g. MarketSquare)")
    ap.add_argument("--db", default=None, help="explicit path to claude-mem.db")
    ap.add_argument("--out", default=None, help="output .md path (default: ./CLAUDE_MEM_DIGEST.md)")
    args = ap.parse_args(argv)

    db = find_db(args.db)
    if not db:
        print("claude-mem.db not found. Pass --db PATH, or check claude-mem is installed.",
              file=sys.stderr)
        return 1
    try:
        con, tmp = open_readonly_snapshot(db)
    except Exception as e:
        print(f"could not open db read-only: {e}", file=sys.stderr)
        return 2
    try:
        rows, obs_n, total = build(con, args.limit, args.project)
        md = render(rows, obs_n, total, args.limit, args.project)
    finally:
        con.close()
        shutil.rmtree(tmp, ignore_errors=True)

    out = args.out or os.path.join(os.getcwd(), "CLAUDE_MEM_DIGEST.md")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(md)
    print(f"wrote {out}  ({len(md)} bytes, {len(rows)} sessions)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
