# ============================================================================
#  DO NOT EDIT THIS FILE TO ADD YOUR KEYS.  It ASKS you for them when you run it.
#
#  6 Sep 2026: the two Read-Host prompt LABELS below were replaced with the actual
#  credentials and the file saved. It reads like the place to put them -- it is not.
#  The run then prompted with those strings as labels, both inputs came back empty,
#  and the script correctly refused. But the new pair was then sitting in plain text
#  in a TRACKED repo file, one `git add -A` away from GitHub.
#
#  If pasting into a console window is the problem, use the FILE route instead:
#  put the two values on two lines in  .secrets\r2_new_keys.txt  (that folder is
#  gitignored), then run this. It reads them, ships them, and deletes the file.
# ============================================================================
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $root
$log = Join-Path $root ".secrets\hetzner_s3_log.txt"
$srv = "root@178.104.73.239"
function Say($m) { Write-Host $m; Add-Content -Path $log -Value $m }
Say ""; Say ("===== run $(Get-Date -Format s) =====")
Write-Host ""
Write-Host "  Paste the new CLOUDFLARE R2 credentials."
Write-Host "  (The variables are NAMED HETZNER_S3_* for historical reasons, but the"
Write-Host "   endpoint is r2.cloudflarestorage.com - R2 is what they authenticate to.)"
Write-Host "  Neither value is stored on this PC or shown to Claude."
Write-Host ""
$keyFile = Join-Path $root ".secrets\r2_new_keys.txt"
if (Test-Path $keyFile) {
  $lines = @(Get-Content $keyFile | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne "" })
  if ($lines.Count -ge 2) {
    $ak = $lines[0] -replace '\s',''
    $sk = $lines[1] -replace '\s',''
    Write-Host "  Read both values from .secrets\r2_new_keys.txt (deleted after sending)."
  }
}
if (-not $ak -or -not $sk) {
  Write-Host "  Paste with Ctrl+V. The text IS visible - if nothing appears, it did not paste."
  $ak = (Read-Host "  ACCESS KEY") -replace '\s',''
  $sk = (Read-Host "  SECRET KEY") -replace '\s',''
}
Say ("  access key: {0} chars | secret key: {1} chars" -f $ak.Length, $sk.Length)
if ($ak.Length -lt 8 -or $sk.Length -lt 8) { Say "  [X] one of those is too short - nothing sent."; Read-Host "  Press Enter to close"; exit 1 }
if ($ak.Length -eq 20) {
  Say "  [X] a 20-character access key is a HETZNER credential. This lane talks to"
  Say "      Cloudflare R2, which issues 32-character Access Key IDs. Nothing sent -"
  Say "      get the pair from Cloudflare: R2 > Manage R2 API Tokens > Object Read & Write."
  Read-Host "  Press Enter to close"; exit 1
}
if ($ak.Length -ne 32) { Say "  [!] R2 access keys are normally 32 characters, this is $($ak.Length) - shipping anyway, the S3 call will judge it" }
Say "  [OK] shipping."
& scp -q "scripts\install_hetzner_s3.py" "${srv}:/tmp/install_hetzner_s3.py" 2>&1 | ForEach-Object { Say $_ }
if ($LASTEXITCODE -ne 0) { Say "  [X] could not reach the server"; Read-Host "  Press Enter to close"; exit 1 }
& ssh $srv "python3 /tmp/install_hetzner_s3.py '$ak' '$sk'; rm -f /tmp/install_hetzner_s3.py" 2>&1 | ForEach-Object { Say $_ }
if (Test-Path $keyFile) {
  Remove-Item $keyFile -Force
  Write-Host "  Deleted .secrets\r2_new_keys.txt - a transit buffer, never a store."
}
Say ""; Say "  Done - Claude reads .secrets\hetzner_s3_log.txt directly."
Read-Host "  Press Enter to close"
