#!/usr/bin/env python3
"""apply_lang_country.py -- LANG-COUNTRY-1 (5 Oct 2026).

David asked: "are the Quick app correctly listing in the US, UK and AUS in their language as
selectable language options?" PROBED 5 Oct 2026 in a browser at ?cc=US / GB / AU: NO. Every
country was offered South Africa's five (English, isiZulu, isiXhosa, Afrikaans, Sepedi) on the
door row and in the top-bar menu, and a New York cleaner's "Languages I work in" chips were
the South African list. QLANGS was hard-coded once, before the country pack ever ran.

What the rulings say the app must show (no new decision here, only obedience):
  RUL-162(c) / RUL-165(b): per-country lists approved; outside ZA every local language is
  'prepared' -- built, NOT offered -- until David's ZA assessment; English stays on everywhere.
  RUL-151: the language she SPEAKS is a matching signal seeded PER COUNTRY (not a translation,
  so no sign-off gate applies to it).

So:
  (a) the app languages a visitor can pick = that country's 'offered' list in
      roles/lang_countries.json (today: ZA five; every other country English only), and with
      one language the row and the top-bar button are not shown at all;
  (b) "Languages I work in" = that country's approved list (all statuses), English first;
  (c) a remembered/phone language not offered in her country falls back to English.
The table is generated from roles/lang_countries.json at apply time -- one source. Re-run this
script after changing that file (e.g. the day David switches a country's languages on).

Idempotent: replaces its own generated block. Asserts every anchor. Copies quick.html over
genie/HARNESS.html (the two are kept identical, RUL-162(d)).
"""
import json, os, re, shutil, sys, datetime

HERE = os.path.dirname(os.path.abspath(__file__))
MS = os.path.dirname(HERE)
Q = os.path.join(MS, 'quick.html')
H = os.path.join(MS, 'genie', 'HARNESS.html')
L = json.load(open(os.path.join(MS, 'roles', 'lang_countries.json'), encoding='utf-8'))

names = L['names']
offered, speaks = {}, {}
for cc, row in L['countries'].items():
    codes = [c for c, st in row['langs'] if st == 'offered']
    if 'en' not in codes:
        codes.insert(0, 'en')
    offered[cc] = codes
    sp = ['English'] + [names.get(c, c) for c, st in row['langs'] if c != 'en']
    speaks[cc] = sp

src = open(Q, encoding='utf-8').read()
orig = src

BEGIN, END = '/* LANG-COUNTRY-1:BEGIN', '/* LANG-COUNTRY-1:END */'
block = (BEGIN + ' -- generated by scripts/apply_lang_country.py from roles/lang_countries.json; do not edit.\n'
         '       RUL-162/165: the app offers only the languages switched on for HER country (outside ZA: English\n'
         '       until David switches them on); RUL-151: "Languages I work in" is seeded from her country\'s list. */\n'
         '    try{\n'
         '      var _LOFF=' + json.dumps(offered, ensure_ascii=False, separators=(',', ':')) + ';\n'
         '      var _LSPK=' + json.dumps(speaks, ensure_ascii=False, separators=(',', ':')) + ';\n'
         '      if(!window.QLANGS_ALL) window.QLANGS_ALL=QLANGS.slice();\n'
         '      if(!window.SVC_SPEAKS_ZA) window.SVC_SPEAKS_ZA=[SVC_SPEAKS_MAIN.slice(), SVC_SPEAKS_MORE.slice()];\n'
         '      var _off=_LOFF[QCC]||[\'en\'];\n'
         '      QLANGS=QLANGS_ALL.filter(function(x){ return _off.indexOf(x[0])>=0; });\n'
         '      if(!QLANGS.length) QLANGS=[[\'en\',\'English\']];\n'
         '      if(_off.indexOf(QLANG)<0){ QLANG=\'en\'; document.documentElement.lang=\'en\'; }\n'
         '      if(QCC===\'ZA\'){ SVC_SPEAKS_MAIN=SVC_SPEAKS_ZA[0].slice(); SVC_SPEAKS_MORE=SVC_SPEAKS_ZA[1].slice(); }\n'
         '      else { SVC_SPEAKS_MAIN=(_LSPK[QCC]||[\'English\']).slice(); SVC_SPEAKS_MORE=[]; }\n'
         '    }catch(_){}\n'
         '    ' + END)

# (a) at the end of applyPack -- runs on load and on every country change
if BEGIN in src:
    src = re.sub(re.escape(BEGIN) + r'.*?' + re.escape(END), lambda m: block, src, flags=re.S)
else:
    anchor = ("    else { LOC.city=QP['default']; LOC.suburb=QP.cities[QP['default']][0]; }\n"
              "  }\n  window.qPackDestKey")
    assert src.count(anchor) == 1, 'applyPack anchor'
    src = src.replace(anchor, "    else { LOC.city=QP['default']; LOC.suburb=QP.cities[QP['default']][0]; }\n    "
                      + block + "\n  }\n  window.qPackDestKey")

# (b) the door's language row: not shown when her country has one language
a = "    sc.insertAdjacentHTML('beforeend','<div class=\"langrow\""
if "if(QLANGS.length>1) sc.insertAdjacentHTML('beforeend','<div class=\"langrow\"" not in src:
    assert src.count(a) == 1, 'langrow anchor'
    src = src.replace(a, "    if(QLANGS.length>1) sc.insertAdjacentHTML('beforeend','<div class=\"langrow\"")

# (c) the top-bar language button: hidden when there is nothing to switch to
a = ("    var bar=document.querySelector('.bar'); if(!bar) return;\n"
     "    var w=document.getElementById('qlbw'), b=document.getElementById('qlb');\n")
g = "    if(QLANGS.length<2){ if(w) w.style.display='none'; return; } else if(w) w.style.display='';   /* LANG-COUNTRY-1 */\n"
if g not in src:
    assert src.count(a) == 1, 'top-bar anchor'
    src = src.replace(a, a + g)

# (d) "More" only when there is more to show
a = "    +(open?'':'<button class=\"chip\" data-more=\"1\">More</button>');"
b = "    +((open||!SVC_SPEAKS_MORE.length)?'':'<button class=\"chip\" data-more=\"1\">More</button>');"
if b not in src:
    assert src.count(a) == 1, 'more anchor'
    src = src.replace(a, b)

if src != orig:
    ts = datetime.datetime.now().strftime('%Y%m%d-%H%M%S')
    shutil.copy2(Q, Q + '.bak-langcountry-' + ts)
    shutil.copy2(H, H + '.bak-langcountry-' + ts)
    with open(Q, 'w', encoding='utf-8', newline='') as fh:
        fh.write(src)
    shutil.copyfile(Q, H)
    print('LANG-COUNTRY-1 applied; HARNESS synced. offered:', offered)
else:
    print('LANG-COUNTRY-1 already applied; nothing changed.')
