#!/usr/bin/env python3
"""apply_trainers_i18n.py -- TRAINERS-DOOR-1 (RUL-217): the Trainers door's words in all 15 of Quick's languages.

Claude's first drafts (RUL-160), 10 Oct 2026, like the rest of roles/quick_i18n.json: for David's readers and the Language
reviewer. Adds only keys that are not there yet -- a reader's correction already in the file is never overwritten.
Columns follow quick_i18n.json 'langs': af zu st xh nso es zh tl vi cy pl ro pa ar yue.
Run:  python3 scripts/apply_trainers_i18n.py   then   python3 scripts/sync_quick_roles.py
"""
import io, json, os, shutil, time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
F = os.path.join(ROOT, "roles", "quick_i18n.json")
LANGS = ["af", "zu", "st", "xh", "nso", "es", "zh", "tl", "vi", "cy", "pl", "ro", "pa", "ar", "yue"]

ROWS = """
Personal trainer|Persoonlike afrigter|Umqeqeshi womuntu siqu|Mokwetlisi wa motho ka mong|Umqeqeshi womntu ngamnye|Mohlahli wa motho ka noši|Entrenador personal|私人教练|Personal trainer|Huấn luyện viên cá nhân|Hyfforddwr personol|Trener personalny|Antrenor personal|ਪਰਸਨਲ ਟ੍ਰੇਨਰ|مدرب شخصي|私人教練
Aerobics instructor|Aërobiese instrukteur|Umqeqeshi we-aerobics|Mokwetlisi wa aerobics|Umqeqeshi we-aerobics|Mohlahli wa aerobics|Instructor de aeróbicos|有氧操教练|Aerobics instructor|Huấn luyện viên thể dục nhịp điệu|Hyfforddwr aerobeg|Instruktor aerobiku|Instructor de aerobic|ਐਰੋਬਿਕਸ ਇੰਸਟ੍ਰਕਟਰ|مدرب أيروبكس|健身操教練
Dance fitness instructor|Dansfiksheid-instrukteur|Umqeqeshi womdanso wokuqina|Mokwetlisi wa ho tantsha bakeng sa boitekiso|Umqeqeshi womdaniso wokomelela|Mohlahli wa go bina go itšhidulla|Instructor de baile fitness|舞蹈健身教练|Dance fitness instructor|Huấn luyện viên nhảy thể dục|Hyfforddwr dawns ffitrwydd|Instruktor fitnessu tanecznego|Instructor de dans fitness|ਡਾਂਸ ਫਿਟਨੈੱਸ ਇੰਸਟ੍ਰਕਟਰ|مدرب لياقة بالرقص|舞蹈健身教練
Yoga instructor|Joga-instrukteur|Umqeqeshi we-yoga|Mokwetlisi wa yoga|Umqeqeshi we-yoga|Mohlahli wa yoga|Instructor de yoga|瑜伽教练|Yoga instructor|Huấn luyện viên yoga|Hyfforddwr ioga|Instruktor jogi|Instructor de yoga|ਯੋਗਾ ਇੰਸਟ੍ਰਕਟਰ|مدرب يوغا|瑜伽導師
Pilates instructor|Pilates-instrukteur|Umqeqeshi we-Pilates|Mokwetlisi wa Pilates|Umqeqeshi we-Pilates|Mohlahli wa Pilates|Instructor de pilates|普拉提教练|Pilates instructor|Huấn luyện viên Pilates|Hyfforddwr Pilates|Instruktor pilatesu|Instructor de Pilates|ਪਿਲਾਟੇਸ ਇੰਸਟ੍ਰਕਟਰ|مدرب بيلاتس|普拉提導師
Functional fitness coach|Funksionele fiksheidsafrigter|Umqeqeshi wokuqina komzimba|Mokwetlisi wa boitekiso ba mmele|Umqeqeshi wokomelela komzimba|Mohlahli wa go itšhidulla ga mmele|Entrenador de fitness funcional|功能性健身教练|Functional fitness coach|Huấn luyện viên thể lực chức năng|Hyfforddwr ffitrwydd gweithredol|Trener treningu funkcjonalnego|Antrenor de fitness funcțional|ਫੰਕਸ਼ਨਲ ਫਿਟਨੈੱਸ ਕੋਚ|مدرب لياقة وظيفية|功能性健身教練
Strength & conditioning coach|Krag- en kondisioneringsafrigter|Umqeqeshi wamandla nokuqina|Mokwetlisi wa matla le boitekiso|Umqeqeshi wamandla nokomelela|Mohlahli wa maatla le go itokišetša|Entrenador de fuerza y acondicionamiento|体能与力量教练|Strength & conditioning coach|Huấn luyện viên sức mạnh và thể lực|Hyfforddwr cryfder a chyflyru|Trener przygotowania motorycznego|Antrenor de forță și condiție fizică|ਤਾਕਤ ਅਤੇ ਕੰਡੀਸ਼ਨਿੰਗ ਕੋਚ|مدرب القوة والإعداد البدني|體能及力量教練
Boxing coach|Boksafrigter|Umqeqeshi wesibhakela|Mokwetlisi wa ditebele|Umqeqeshi wamanqindi|Mohlahli wa matswele|Entrenador de boxeo|拳击教练|Coach ng boksing|Huấn luyện viên quyền anh|Hyfforddwr bocsio|Trener boksu|Antrenor de box|ਮੁੱਕੇਬਾਜ਼ੀ ਕੋਚ|مدرب ملاكمة|拳擊教練
Kickboxing coach|Skopboksafrigter|Umqeqeshi we-kickboxing|Mokwetlisi wa kickboxing|Umqeqeshi we-kickboxing|Mohlahli wa kickboxing|Entrenador de kickboxing|搏击教练|Coach ng kickboxing|Huấn luyện viên kickboxing|Hyfforddwr cic-focsio|Trener kickboxingu|Antrenor de kickboxing|ਕਿੱਕਬਾਕਸਿੰਗ ਕੋਚ|مدرب كيك بوكسينغ|搏擊教練
Wrestling coach|Stoei-afrigter|Umqeqeshi we-wrestling|Mokwetlisi wa ho kwalla|Umqeqeshi we-wrestling|Mohlahli wa go katana|Entrenador de lucha|摔跤教练|Coach ng wrestling|Huấn luyện viên đấu vật|Hyfforddwr reslo|Trener zapasów|Antrenor de lupte|ਕੁਸ਼ਤੀ ਕੋਚ|مدرب مصارعة|摔角教練
Judo instructor|Judo-instrukteur|Umqeqeshi we-judo|Mokwetlisi wa judo|Umqeqeshi we-judo|Mohlahli wa judo|Instructor de judo|柔道教练|Judo instructor|Huấn luyện viên judo|Hyfforddwr jiwdo|Instruktor judo|Instructor de judo|ਜੂਡੋ ਇੰਸਟ੍ਰਕਟਰ|مدرب جودو|柔道教練
Karate instructor|Karate-instrukteur|Umqeqeshi we-karate|Mokwetlisi wa karate|Umqeqeshi we-karate|Mohlahli wa karate|Instructor de kárate|空手道教练|Karate instructor|Huấn luyện viên karate|Hyfforddwr karate|Instruktor karate|Instructor de karate|ਕਰਾਟੇ ਇੰਸਟ੍ਰਕਟਰ|مدرب كاراتيه|空手道教練
Taekwondo instructor|Taekwondo-instrukteur|Umqeqeshi we-taekwondo|Mokwetlisi wa taekwondo|Umqeqeshi we-taekwondo|Mohlahli wa taekwondo|Instructor de taekwondo|跆拳道教练|Taekwondo instructor|Huấn luyện viên taekwondo|Hyfforddwr taekwondo|Instruktor taekwondo|Instructor de taekwondo|ਤਾਈਕਵਾਂਡੋ ਇੰਸਟ੍ਰਕਟਰ|مدرب تايكوندو|跆拳道教練
Jiu-jitsu instructor|Jiu-jitsu-instrukteur|Umqeqeshi we-jiu-jitsu|Mokwetlisi wa jiu-jitsu|Umqeqeshi we-jiu-jitsu|Mohlahli wa jiu-jitsu|Instructor de jiu-jitsu|柔术教练|Jiu-jitsu instructor|Huấn luyện viên jiu-jitsu|Hyfforddwr jiu-jitsu|Instruktor jiu-jitsu|Instructor de jiu-jitsu|ਜੀਊ-ਜਿਤਸੂ ਇੰਸਟ੍ਰਕਟਰ|مدرب جوجيتسو|柔術教練
MMA coach|MMA-afrigter|Umqeqeshi we-MMA|Mokwetlisi wa MMA|Umqeqeshi we-MMA|Mohlahli wa MMA|Entrenador de MMA|综合格斗教练|Coach ng MMA|Huấn luyện viên MMA|Hyfforddwr MMA|Trener MMA|Antrenor de MMA|MMA ਕੋਚ|مدرب فنون قتالية مختلطة|綜合格鬥教練
Fencing coach|Skermafrigter|Umqeqeshi wokubiyela ngenkemba|Mokwetlisi wa ho lwana ka sabole|Umqeqeshi wokulwa ngekrele|Mohlahli wa go lwa ka tšhoša|Entrenador de esgrima|击剑教练|Coach ng fencing|Huấn luyện viên đấu kiếm|Hyfforddwr cleddyfaeth|Trener szermierki|Antrenor de scrimă|ਤਲਵਾਰਬਾਜ਼ੀ ਕੋਚ|مدرب مبارزة|劍擊教練
Soccer coach|Sokkerafrigter|Umqeqeshi webhola lezinyawo|Mokwetlisi wa bolo ya maoto|Umqeqeshi webhola ekhatywayo|Mohlahli wa kgwele ya maoto|Entrenador de fútbol|足球教练|Coach ng soccer|Huấn luyện viên bóng đá|Hyfforddwr pêl-droed|Trener piłki nożnej|Antrenor de fotbal|ਫੁੱਟਬਾਲ ਕੋਚ|مدرب كرة قدم|足球教練
Rugby coach|Rugbyafrigter|Umqeqeshi werugby|Mokwetlisi wa rugby|Umqeqeshi werugby|Mohlahli wa rugby|Entrenador de rugby|橄榄球教练|Coach ng rugby|Huấn luyện viên bóng bầu dục|Hyfforddwr rygbi|Trener rugby|Antrenor de rugby|ਰਗਬੀ ਕੋਚ|مدرب رغبي|欖球教練
Cricket coach|Krieketafrigter|Umqeqeshi wekhilikithi|Mokwetlisi wa krikete|Umqeqeshi weqakamba|Mohlahli wa krikete|Entrenador de críquet|板球教练|Coach ng cricket|Huấn luyện viên cricket|Hyfforddwr criced|Trener krykieta|Antrenor de cricket|ਕ੍ਰਿਕਟ ਕੋਚ|مدرب كريكت|板球教練
Hockey coach|Hokkie-afrigter|Umqeqeshi wehokhi|Mokwetlisi wa hockey|Umqeqeshi wehoki|Mohlahli wa hockey|Entrenador de hockey|曲棍球教练|Coach ng hockey|Huấn luyện viên khúc côn cầu|Hyfforddwr hoci|Trener hokeja|Antrenor de hochei|ਹਾਕੀ ਕੋਚ|مدرب هوكي|曲棍球教練
Netball coach|Netbalafrigter|Umqeqeshi we-netball|Mokwetlisi wa netball|Umqeqeshi womnyazi|Mohlahli wa netball|Entrenador de netball|无板篮球教练|Coach ng netball|Huấn luyện viên bóng lưới|Hyfforddwr pêl-rwyd|Trener netballu|Antrenor de netball|ਨੈੱਟਬਾਲ ਕੋਚ|مدرب كرة الشبكة|投球教練
Basketball coach|Basketbalafrigter|Umqeqeshi we-basketball|Mokwetlisi wa basketball|Umqeqeshi webhola yomnyazi|Mohlahli wa basketball|Entrenador de baloncesto|篮球教练|Coach ng basketball|Huấn luyện viên bóng rổ|Hyfforddwr pêl-fasged|Trener koszykówki|Antrenor de baschet|ਬਾਸਕਟਬਾਲ ਕੋਚ|مدرب كرة سلة|籃球教練
Volleyball coach|Vlugbalafrigter|Umqeqeshi we-volleyball|Mokwetlisi wa volleyball|Umqeqeshi we-volleyball|Mohlahli wa volleyball|Entrenador de voleibol|排球教练|Coach ng volleyball|Huấn luyện viên bóng chuyền|Hyfforddwr pêl-foli|Trener siatkówki|Antrenor de volei|ਵਾਲੀਬਾਲ ਕੋਚ|مدرب كرة طائرة|排球教練
Baseball coach|Bofbalafrigter|Umqeqeshi we-baseball|Mokwetlisi wa baseball|Umqeqeshi we-baseball|Mohlahli wa baseball|Entrenador de béisbol|棒球教练|Coach ng baseball|Huấn luyện viên bóng chày|Hyfforddwr pêl-fas|Trener baseballu|Antrenor de baseball|ਬੇਸਬਾਲ ਕੋਚ|مدرب بيسبول|棒球教練
American football coach|Amerikaanse voetbalafrigter|Umqeqeshi webhola laseMelika|Mokwetlisi wa bolo ya Amerika|Umqeqeshi webhola yaseMelika|Mohlahli wa kgwele ya Amerika|Entrenador de fútbol americano|美式橄榄球教练|Coach ng American football|Huấn luyện viên bóng bầu dục Mỹ|Hyfforddwr pêl-droed Americanaidd|Trener futbolu amerykańskiego|Antrenor de fotbal american|ਅਮਰੀਕੀ ਫੁੱਟਬਾਲ ਕੋਚ|مدرب كرة قدم أمريكية|美式足球教練
Tennis coach|Tennisafrigter|Umqeqeshi wethenisi|Mokwetlisi wa tennis|Umqeqeshi wentenetya|Mohlahli wa thenese|Entrenador de tenis|网球教练|Coach ng tennis|Huấn luyện viên quần vợt|Hyfforddwr tennis|Trener tenisa|Antrenor de tenis|ਟੈਨਿਸ ਕੋਚ|مدرب تنس|網球教練
Squash coach|Muurbalafrigter|Umqeqeshi we-squash|Mokwetlisi wa squash|Umqeqeshi we-squash|Mohlahli wa squash|Entrenador de squash|壁球教练|Coach ng squash|Huấn luyện viên bóng quần|Hyfforddwr sboncen|Trener squasha|Antrenor de squash|ਸਕੁਐਸ਼ ਕੋਚ|مدرب إسكواش|壁球教練
Padel coach|Padel-afrigter|Umqeqeshi we-padel|Mokwetlisi wa padel|Umqeqeshi we-padel|Mohlahli wa padel|Entrenador de pádel|板式网球教练|Coach ng padel|Huấn luyện viên padel|Hyfforddwr padel|Trener padla|Antrenor de padel|ਪੈਡਲ ਕੋਚ|مدرب بادل|板式網球教練
Badminton coach|Pluimbalafrigter|Umqeqeshi we-badminton|Mokwetlisi wa badminton|Umqeqeshi we-badminton|Mohlahli wa badminton|Entrenador de bádminton|羽毛球教练|Coach ng badminton|Huấn luyện viên cầu lông|Hyfforddwr badminton|Trener badmintona|Antrenor de badminton|ਬੈਡਮਿੰਟਨ ਕੋਚ|مدرب ريشة طائرة|羽毛球教練
Table tennis coach|Tafeltennisafrigter|Umqeqeshi wethenisi yetafula|Mokwetlisi wa tennis ya tafole|Umqeqeshi wentenetya yetafile|Mohlahli wa thenese ya tafola|Entrenador de tenis de mesa|乒乓球教练|Coach ng table tennis|Huấn luyện viên bóng bàn|Hyfforddwr tennis bwrdd|Trener tenisa stołowego|Antrenor de tenis de masă|ਟੇਬਲ ਟੈਨਿਸ ਕੋਚ|مدرب تنس الطاولة|乒乓波教練
Golf coach|Gholfafrigter|Umqeqeshi wegalufu|Mokwetlisi wa kolofo|Umqeqeshi wegalufa|Mohlahli wa kolofo|Entrenador de golf|高尔夫教练|Coach ng golf|Huấn luyện viên golf|Hyfforddwr golff|Trener golfa|Antrenor de golf|ਗੋਲਫ ਕੋਚ|مدرب غولف|高爾夫球教練
Archery coach|Boogskietafrigter|Umqeqeshi wokucibisheka ngomnsalo|Mokwetlisi wa ho thunya ka seqha|Umqeqeshi wokudubula ngesaphetha|Mohlahli wa go thunya ka bora|Entrenador de tiro con arco|射箭教练|Coach ng archery|Huấn luyện viên bắn cung|Hyfforddwr saethyddiaeth|Trener łucznictwa|Antrenor de tir cu arcul|ਤੀਰਅੰਦਾਜ਼ੀ ਕੋਚ|مدرب رماية بالقوس|射箭教練
Swimming coach|Swemafrigter|Umqeqeshi wokubhukuda|Mokwetlisi wa ho sesa|Umqeqeshi wokuqubha|Mohlahli wa go rutha|Entrenador de natación|游泳教练|Coach ng paglangoy|Huấn luyện viên bơi lội|Hyfforddwr nofio|Trener pływania|Antrenor de înot|ਤੈਰਾਕੀ ਕੋਚ|مدرب سباحة|游泳教練
Diving instructor|Duikinstrukteur|Umqeqeshi wokutshuza|Mokwetlisi wa ho qwela|Umqeqeshi wokuntywila|Mohlahli wa go ina|Instructor de buceo|潜水教练|Diving instructor|Huấn luyện viên lặn|Hyfforddwr plymio|Instruktor nurkowania|Instructor de scufundări|ਗੋਤਾਖੋਰੀ ਇੰਸਟ੍ਰਕਟਰ|مدرب غوص|潛水教練
Surfing coach|Branderplankafrigter|Umqeqeshi we-surfing|Mokwetlisi wa surfing|Umqeqeshi we-surfing|Mohlahli wa surfing|Entrenador de surf|冲浪教练|Coach ng surfing|Huấn luyện viên lướt sóng|Hyfforddwr syrffio|Trener surfingu|Antrenor de surf|ਸਰਫ਼ਿੰਗ ਕੋਚ|مدرب ركوب الأمواج|滑浪教練
Rowing & canoeing coach|Roei- en kano-afrigter|Umqeqeshi wokugwedla nesikebhe|Mokwetlisi wa ho soka seketswana|Umqeqeshi wokubheqa nephenyane|Mohlahli wa go hlahla sekepe|Entrenador de remo y piragüismo|赛艇与皮划艇教练|Coach ng paggaod at canoe|Huấn luyện viên chèo thuyền|Hyfforddwr rhwyfo a chanŵio|Trener wioślarstwa i kajakarstwa|Antrenor de canotaj și caiac-canoe|ਰੋਇੰਗ ਅਤੇ ਕੈਨੋਇੰਗ ਕੋਚ|مدرب تجديف وكانو|賽艇及獨木舟教練
Sailing instructor|Seilinstrukteur|Umqeqeshi wokuhamba ngomkhumbi oneseyili|Mokwetlisi wa sekepe sa seile|Umqeqeshi wokuhamba ngesikhephe|Mohlahli wa sekepe sa seila|Instructor de vela|帆船教练|Sailing instructor|Huấn luyện viên thuyền buồm|Hyfforddwr hwylio|Instruktor żeglarstwa|Instructor de navigație cu vele|ਸੇਲਿੰਗ ਇੰਸਟ੍ਰਕਟਰ|مدرب إبحار شراعي|帆船教練
Running & athletics coach|Hardloop- en atletiekafrigter|Umqeqeshi wokugijima nezemidlalo|Mokwetlisi wa ho matha le dipapadi|Umqeqeshi wokubaleka neembaleki|Mohlahli wa go kitima le dipapadi|Entrenador de running y atletismo|跑步与田径教练|Coach ng pagtakbo at athletics|Huấn luyện viên chạy bộ và điền kinh|Hyfforddwr rhedeg ac athletau|Trener biegania i lekkoatletyki|Antrenor de alergare și atletism|ਦੌੜ ਅਤੇ ਐਥਲੈਟਿਕਸ ਕੋਚ|مدرب جري وألعاب قوى|跑步及田徑教練
Cycling coach|Fietsryafrigter|Umqeqeshi wokugibela ibhayisikili|Mokwetlisi wa ho palama baesekele|Umqeqeshi wokukhwela ibhayisekile|Mohlahli wa go nametša paesekela|Entrenador de ciclismo|自行车教练|Coach ng pagbibisikleta|Huấn luyện viên đạp xe|Hyfforddwr beicio|Trener kolarstwa|Antrenor de ciclism|ਸਾਈਕਲਿੰਗ ਕੋਚ|مدرب ركوب الدراجات|單車教練
Triathlon coach|Driekamp-afrigter|Umqeqeshi we-triathlon|Mokwetlisi wa triathlon|Umqeqeshi we-triathlon|Mohlahli wa triathlon|Entrenador de triatlón|铁人三项教练|Coach ng triathlon|Huấn luyện viên ba môn phối hợp|Hyfforddwr triathlon|Trener triathlonu|Antrenor de triatlon|ਟ੍ਰਾਈਥਲੋਨ ਕੋਚ|مدرب ترايثلون|三項鐵人教練
Horse riding instructor|Perdry-instrukteur|Umqeqeshi wokugibela amahhashi|Mokwetlisi wa ho palama dipere|Umqeqeshi wokukhwela amahashe|Mohlahli wa go nametša dipere|Instructor de equitación|马术教练|Horse riding instructor|Huấn luyện viên cưỡi ngựa|Hyfforddwr marchogaeth|Instruktor jazdy konnej|Instructor de echitație|ਘੋੜਸਵਾਰੀ ਇੰਸਟ੍ਰਕਟਰ|مدرب ركوب الخيل|馬術教練
Climbing instructor|Klim-instrukteur|Umqeqeshi wokuqwala|Mokwetlisi wa ho hlwa|Umqeqeshi wokunyuka|Mohlahli wa go namela|Instructor de escalada|攀岩教练|Climbing instructor|Huấn luyện viên leo núi|Hyfforddwr dringo|Instruktor wspinaczki|Instructor de escaladă|ਚੜ੍ਹਾਈ ਇੰਸਟ੍ਰਕਟਰ|مدرب تسلق|攀石教練
Skating coach|Skaats-afrigter|Umqeqeshi wokushibilika|Mokwetlisi wa ho thella|Umqeqeshi wokutyibilika|Mohlahli wa go thelela|Entrenador de patinaje|滑冰教练|Coach ng skating|Huấn luyện viên trượt băng|Hyfforddwr sglefrio|Trener łyżwiarstwa|Antrenor de patinaj|ਸਕੇਟਿੰਗ ਕੋਚ|مدرب تزلج|溜冰教練
Ski & snowboard instructor|Ski- en sneeuplankinstrukteur|Umqeqeshi wokushushuluza eqhweni|Mokwetlisi wa ho thella lehloeng|Umqeqeshi wokutyibilika ekhephini|Mohlahli wa go thelela lehlweng|Instructor de esquí y snowboard|滑雪与单板教练|Ski & snowboard instructor|Huấn luyện viên trượt tuyết|Hyfforddwr sgïo ac eirafyrddio|Instruktor narciarstwa i snowboardu|Instructor de schi și snowboard|ਸਕੀ ਅਤੇ ਸਨੋਬੋਰਡ ਇੰਸਟ੍ਰਕਟਰ|مدرب تزلج على الثلج|滑雪教練
Gymnastics coach|Gimnastiekafrigter|Umqeqeshi wezokuzivocavoca|Mokwetlisi wa gymnastics|Umqeqeshi we-gymnastics|Mohlahli wa gymnastics|Entrenador de gimnasia|体操教练|Coach ng gymnastics|Huấn luyện viên thể dục dụng cụ|Hyfforddwr gymnasteg|Trener gimnastyki|Antrenor de gimnastică|ਜਿਮਨਾਸਟਿਕਸ ਕੋਚ|مدرب جمباز|體操教練
Acrobatics coach|Akrobatiekafrigter|Umqeqeshi we-acrobatics|Mokwetlisi wa acrobatics|Umqeqeshi we-acrobatics|Mohlahli wa acrobatics|Entrenador de acrobacia|杂技教练|Coach ng acrobatics|Huấn luyện viên nhào lộn|Hyfforddwr acrobateg|Trener akrobatyki|Antrenor de acrobație|ਕਲਾਬਾਜ਼ੀ ਕੋਚ|مدرب ألعاب بهلوانية|雜技教練
Chess coach|Skaakafrigter|Umqeqeshi we-chess|Mokwetlisi wa chess|Umqeqeshi we-chess|Mohlahli wa chess|Entrenador de ajedrez|国际象棋教练|Coach ng chess|Huấn luyện viên cờ vua|Hyfforddwr gwyddbwyll|Trener szachowy|Antrenor de șah|ਸ਼ਤਰੰਜ ਕੋਚ|مدرب شطرنج|國際象棋教練
Fitness & gym|Fiksheid & gimnasium|Ukuqina nejimu|Boitekiso le jimi|Ukomelela nejimu|Go itšhidulla le jimi|Fitness y gimnasio|健身与健身房|Fitness at gym|Thể hình & phòng tập|Ffitrwydd a champfa|Fitness i siłownia|Fitness și sală|ਫਿਟਨੈੱਸ ਅਤੇ ਜਿਮ|اللياقة والصالة الرياضية|健身及健身室
Combat sports|Gevegsporte|Imidlalo yokulwa|Dipapadi tsa ntwa|Imidlalo yokulwa|Dipapadi tša ntwa|Deportes de combate|格斗运动|Combat sports|Võ thuật & đối kháng|Chwaraeon ymladd|Sporty walki|Sporturi de luptă|ਲੜਾਈ ਵਾਲੀਆਂ ਖੇਡਾਂ|رياضات قتالية|格鬥運動
Team sports|Spansporte|Imidlalo yamaqembu|Dipapadi tsa dihlopha|Imidlalo yamaqela|Dipapadi tša dihlopha|Deportes de equipo|团队运动|Team sports|Thể thao đồng đội|Chwaraeon tîm|Sporty drużynowe|Sporturi de echipă|ਟੀਮ ਖੇਡਾਂ|رياضات جماعية|團體運動
Racket & target sports|Raket- & teikensporte|Imidlalo yerakhethi neyokuqondisa|Dipapadi tsa rakete le tsa sepheo|Imidlalo yerakethi neyokujolisa|Dipapadi tša rakete le tša nepo|Deportes de raqueta y precisión|球拍与瞄准类运动|Racket at target sports|Thể thao vợt & nhắm bắn|Chwaraeon raced a tharged|Sporty rakietowe i celnościowe|Sporturi cu rachetă și de precizie|ਰੈਕੇਟ ਅਤੇ ਨਿਸ਼ਾਨੇ ਵਾਲੀਆਂ ਖੇਡਾਂ|رياضات المضرب والتصويب|球拍及瞄準運動
Water sports|Watersporte|Imidlalo yasemanzini|Dipapadi tsa metsing|Imidlalo yasemanzini|Dipapadi tša meetseng|Deportes acuáticos|水上运动|Water sports|Thể thao dưới nước|Chwaraeon dŵr|Sporty wodne|Sporturi nautice|ਪਾਣੀ ਦੀਆਂ ਖੇਡਾਂ|رياضات مائية|水上運動
Running, cycling & outdoor|Hardloop, fietsry & buitelug|Ukugijima, ibhayisikili nangaphandle|Ho matha, baesekele le kantle|Ukubaleka, ibhayisekile nangaphandle|Go kitima, paesekela le ka ntle|Running, ciclismo y aire libre|跑步、骑行与户外|Takbo, bisikleta at outdoor|Chạy bộ, đạp xe & ngoài trời|Rhedeg, beicio a'r awyr agored|Bieganie, kolarstwo i outdoor|Alergare, ciclism și în aer liber|ਦੌੜ, ਸਾਈਕਲਿੰਗ ਅਤੇ ਬਾਹਰੀ ਖੇਡਾਂ|الجري وركوب الدراجات والهواء الطلق|跑步、踩單車及戶外
Gymnastics & acrobatics|Gimnastiek & akrobatiek|Ezokuzivocavoca ne-acrobatics|Gymnastics le acrobatics|I-gymnastics ne-acrobatics|Gymnastics le acrobatics|Gimnasia y acrobacia|体操与杂技|Gymnastics at acrobatics|Thể dục dụng cụ & nhào lộn|Gymnasteg ac acrobateg|Gimnastyka i akrobatyka|Gimnastică și acrobație|ਜਿਮਨਾਸਟਿਕਸ ਅਤੇ ਕਲਾਬਾਜ਼ੀ|الجمباز والألعاب البهلوانية|體操及雜技
Mind sports|Breinsporte|Imidlalo yengqondo|Dipapadi tsa kelello|Imidlalo yengqondo|Dipapadi tša monagano|Deportes mentales|智力运动|Mind sports|Thể thao trí tuệ|Chwaraeon meddwl|Sporty umysłowe|Sporturi ale minții|ਦਿਮਾਗੀ ਖੇਡਾਂ|رياضات ذهنية|智力運動
Sport & fitness|Sport & fiksheid|Ezemidlalo nokuqina|Dipapadi le boitekiso|Imidlalo nokomelela|Dipapadi le go itšhidulla|Deporte y fitness|运动与健身|Sports at fitness|Thể thao & thể hình|Chwaraeon a ffitrwydd|Sport i fitness|Sport și fitness|ਖੇਡਾਂ ਅਤੇ ਫਿਟਨੈੱਸ|الرياضة واللياقة|運動及健身
Which kind of sport?|Watter soort sport?|Hlobo luni lwezemidlalo?|Ke papadi ya mofuta ofe?|Luhlobo luni lomdlalo?|Ke papadi ya mohuta mang?|¿Qué tipo de deporte?|哪类运动？|Anong uri ng sport?|Loại thể thao nào?|Pa fath o chwaraeon?|Jaki rodzaj sportu?|Ce fel de sport?|ਕਿਹੜੀ ਕਿਸਮ ਦੀ ਖੇਡ?|أي نوع من الرياضة؟|邊類運動？
Which one do you coach?|Watter een rig jy af?|Yikuphi okuqeqeshayo?|O kwetlisa efe?|Yeyiphi oyiqeqeshayo?|O hlahla efe?|¿Cuál entrenas?|你教哪一项？|Alin ang tinuturo mo?|Bạn huấn luyện môn nào?|Pa un ydych chi'n ei hyfforddi?|Co trenujesz?|Pe care o antrenezi?|ਤੁਸੀਂ ਕਿਹੜੀ ਸਿਖਾਉਂਦੇ ਹੋ?|أيها تدرّب؟|你教邊樣？
Name your sport|Noem jou sport|Bhala igama lomdlalo wakho|Ngola lebitso la papadi ya hao|Bhala igama lomdlalo wakho|Ngwala leina la papadi ya gago|Escribe tu deporte|写下你的运动|Isulat ang iyong sport|Ghi tên môn thể thao|Enwch eich camp|Wpisz swój sport|Scrie sportul tău|ਆਪਣੀ ਖੇਡ ਲਿਖੋ|اكتب رياضتك|寫低你嘅運動
Where do you train people?|Waar rig jy mense af?|Ubaqeqeshela kuphi abantu?|O kwetlisa batho kae?|Ubaqeqeshela phi abantu?|O hlahla batho kae?|¿Dónde entrenas a la gente?|你在哪里训练学员？|Saan ka nagsasanay ng tao?|Bạn huấn luyện ở đâu?|Ble ydych chi'n hyfforddi pobl?|Gdzie prowadzisz treningi?|Unde antrenezi oamenii?|ਤੁਸੀਂ ਲੋਕਾਂ ਨੂੰ ਕਿੱਥੇ ਸਿਖਲਾਈ ਦਿੰਦੇ ਹੋ?|أين تدرّب الناس؟|你喺邊度教人？
Per session|Per sessie|Ngesikhathi ngasinye|Ka seshene|Ngeseshoni nganye|Ka seshene|Por sesión|每节课|Bawat session|Mỗi buổi|Y sesiwn|Za sesję|Pe ședință|ਪ੍ਰਤੀ ਸੈਸ਼ਨ|لكل جلسة|每堂
Per month|Per maand|Ngenyanga|Ka kgwedi|Ngenyanga|Ka kgwedi|Por mes|每月|Bawat buwan|Mỗi tháng|Y mis|Za miesiąc|Pe lună|ਪ੍ਰਤੀ ਮਹੀਨਾ|شهريًا|每月
Per package|Per pakket|Ngephakethe|Ka sephutheloana|Ngepakethi|Ka sephuthelwana|Por paquete|每套课程|Bawat package|Mỗi gói|Y pecyn|Za pakiet|Pe pachet|ਪ੍ਰਤੀ ਪੈਕੇਜ|لكل باقة|每套課程
Your session rate|Jou sessietarief|Inani lakho ngesikhathi ngasinye|Tjhelete ya hao ka seshene|Ixabiso lakho ngeseshoni|Tefo ya gago ka seshene|Tu tarifa por sesión|你的每节课收费|Ang singil mo bawat session|Giá mỗi buổi của bạn|Eich pris y sesiwn|Twoja stawka za sesję|Tariful tău pe ședință|ਤੁਹਾਡਾ ਪ੍ਰਤੀ ਸੈਸ਼ਨ ਰੇਟ|سعرك لكل جلسة|你每堂嘅收費
I train people in this — list me free|Ek rig mense hierin af — lys my gratis|Ngiqeqesha abantu kulokhu — ngifake mahhala|Ke kwetlisa batho ho sena — nkenya mahala|Ndiqeqesha abantu kule nto — ndifake simahla|Ke hlahla batho go se — ntsenye mahala|Entreno a gente en esto — publícame gratis|我教这个 — 免费帮我上架|Nagsasanay ako rito — ilista ako nang libre|Tôi huấn luyện môn này — đăng miễn phí|Dw i'n hyfforddi pobl yn hyn — rhestrwch fi am ddim|Trenuję w tym ludzi — dodaj mnie za darmo|Antrenez oameni în asta — listează-mă gratuit|ਮੈਂ ਇਸ ਵਿੱਚ ਸਿਖਲਾਈ ਦਿੰਦਾ ਹਾਂ — ਮੈਨੂੰ ਮੁਫ਼ਤ ਸੂਚੀਬੱਧ ਕਰੋ|أدرّب الناس في هذا — أدرجني مجانًا|我教呢樣 — 免費幫我上架
"""


def rows():
    out = []
    for ln in ROWS.strip().split("\n"):
        c = ln.split("|")
        assert len(c) == 16, "row has %d columns: %s" % (len(c), c[0])
        out.append((c[0], c[1:]))
    return out


def main():
    d = json.load(io.open(F, encoding="utf-8"))
    assert d["langs"] == LANGS, "quick_i18n.json langs changed: %s" % d["langs"]
    shutil.copyfile(F, F + ".bak-trainers-%s" % time.strftime("%Y%m%d-%H%M%S"))
    added = kept = 0
    for en, tr in rows():
        if en in d["w"]:
            kept += 1; continue
        d["w"][en] = tr; added += 1
    io.open(F, "w", encoding="utf-8").write(json.dumps(d, ensure_ascii=False, indent=1))   # the file carries no trailing newline
    print("quick_i18n.json: %d trainer words added, %d already there (kept as they are)" % (added, kept))


if __name__ == "__main__":
    main()
