#!/usr/bin/env python3
"""apply_trainers_quick.py -- TRAINERS-DOOR-1 (RUL-217): the Trainers door inside Quick's Tutors door.

David, 8 Oct 2026: "I would like to do the same for tutors, but for a branch of tutors namely Trainers ... the same flows,
Hows etc ... To also make it Global" / "i agree for it to sit inside Tutors the same as we did for Services".

What this writes into quick.html (and copies to genie/HARNESS.html -- one app in two files):
  * the rate screen learns Per session / Per month / Per package (no wage floor -- RUL-217(c), the RUL-197 class);
  * a TRAINERS-DOOR-1 script: a 'Sport & fitness' tile on the Tutors door's first step (both directions), then
    sport group -> sport (its picture) -> price -> where for a trainer, group -> sport -> where for a finder;
    the advert goes out as category Tutors, service_class Trainers, subject + service_type = the sport's name;
    /quick/?role=<trainer> lands on the price step (the AI example's 'list me free' link);
  * Find asks the server for the sport's AI example (GET /examples/trainers) when nothing real fits.
Idempotent: refuses to apply twice. The TRN_ROLES block itself is generated by scripts/sync_quick_roles.py.
"""
import io, os, shutil, sys, time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
QH = os.path.join(ROOT, "quick.html")
HARN = os.path.join(ROOT, "genie", "HARNESS.html")
MARK = "TRAINERS-DOOR-1 (RUL-217"

DOOR_JS = r"""<script>
/* ===========================================================================
   TRAINERS-DOOR-1 (RUL-217, David 8 Oct 2026): "I would like to do the same for tutors, but for a branch of tutors namely
   Trainers ... Gym, Acrobatics, Aerobics, Wrestling, Chess, Rugby, Soccer, Cricket, Judo, Karate, Running, Golf, Swimming,
   and all of the sports types one can get a trainer for ... the same flows, Hows etc ... To also make it Global" -- and
   "i agree for it to sit inside Tutors the same as we did for Services".
   A DOOR, not a category: a 'Sport & fitness' tile on the Tutors door's first step opens  sport group -> sport (its
   picture) -> price -> where  (5 taps to a draft, RUL-117), or for a finder  group -> sport -> where. The advert goes out
   as category Tutors, service_class Trainers (Trust Score key Tutors-Trainers = the Tutors evidence set), with the
   sport's name as its subject and service_type. A trainer prices per session, per month or per package: a price for
   coaching, not for time, so there is no minimum-wage floor (RUL-217(c), the RUL-197 class). The seventh typed card is
   on every step. Roles, groups and pictures come from roles/role_registry.json (QUICK-TRAINERS block).
   ------------------------------------------------------------------------- */
(function(){
  if(typeof TRN_ROLES==='undefined' || !TRN_ROLES.length) return;
  var TI=-1, i;
  for(i=0;i<CATS.length;i++) if(CATS[i].key==='tutors') TI=i;
  if(TI<0) return;
  var T=CATS[TI];
  TRN_ROLES.forEach(function(r){ PH['role_'+r.k]=PH_BASE+'role_'+r.k+'.jpg?v=photo1'; });   /* TRAINER-PHOTOS-1: new photos, new URL (the CDN and phones keep a picture a year) */
  function trnRole(k){ for(var i=0;i<TRN_ROLES.length;i++) if(TRN_ROLES[i].k===k) return TRN_ROLES[i]; return null; }
  function pickIn(k){ for(var i=picks.length-1;i>=0;i--) if(picks[i].key===k) return picks[i]; return null; }
  function trnOn(){ try{ return cat().key==='tutors' && !!pickIn('tdoor'); }catch(e){ return false; } }
  window.trnRole=trnRole; window.trnOn=trnOn;
  var DOOR={t:'Sport & fitness', p:'role_'+TRN_GROUPS[0].rep, trn:1};
  ['sell','find'].forEach(function(m){
    var st=T[m] && T[m].steps && T[m].steps[0];
    if(st && st.key==='what' && !st.tiles.some(function(x){ return x.trn; })) st.tiles.unshift(DOOR);
  });
  function stepOf(f,k){ for(var i=0;i<f.steps.length;i++) if(f.steps[i].key===k) return f.steps[i]; return null; }
  /* the door tile commits as 'tdoor', so the sport she picks next is the one 'what' every later screen reads */
  var _sop=window.svcOnPick;
  svcOnPick=function(t){
    if(_sop) _sop(t);
    var p=picks[picks.length-1];
    if(t && t.trn && p){ p.key='tdoor'; p.trn=1; }
  };
  function roleTiles(gp){
    var list=TRN_ROLES.filter(function(r){ return gp && r.g===gp.label; });
    if(!list.length && gp){            /* a typed group: the sports whose names share a word with it */
      var w=String(gp.label||'').toLowerCase().split(/[^a-z]+/).filter(function(x){ return x.length>2; });
      list=TRN_ROLES.filter(function(r){ var l=(r.l+' '+r.a.join(' ')).toLowerCase();
        return w.some(function(x){ return l.indexOf(x)>=0; }); }).slice(0,9);
    }
    return list.map(function(r){ return {t:r.l, p:'role_'+r.k, r:r.k}; });
  }
  var _flowT=flow;
  flow=function(){
    if(!trnOn()) return _flowT();
    var find=(mode==='find'), base=find?T.find:T.sell, gp=pickIn('group');
    var steps=[base.steps[0],
      {q:'Which kind of sport?', key:'group', kind:'tile', free:true, freeHint:'Name your sport',
       tiles:TRN_GROUPS.map(function(g){ return {t:g.g, p:'role_'+g.rep, g:g.g}; })},
      {q:find?'Who do you need?':'Which one do you coach?', key:'what', kind:'tile', free:true, freeHint:'Name your sport',
       tiles:roleTiles(gp)}];
    if(!find) steps.push(stepOf(base,'price'));
    steps.push(stepOf(base,'where'));
    return {steps:steps.filter(Boolean)};
  };
  /* RUL-157 for the door: a trainer's advert opens on the sport's picture, never on an area tile's photo */
  var _heroT=heroPhoto;
  heroPhoto=function(){ if(trnOn()){ var r=pickOf('what'); if(r && r.r) return 'role_'+r.r; } return _heroT(); };
  /* the clearance gate (RUL-217(d) / RUL-153): every screen that asks svcRole() for her role's gate -- the draft's
     'It shows in searches once your police clearance is verified' line, the saved screen's live line -- hears it for a
     trainer too. Only while the trainer door is open, so a Services ?role= link never resolves to a sport. */
  var _svrT=svcRole;
  svcRole=function(k){
    var r=_svrT(k); if(r || !trnOn()) return r;
    var t=trnRole(k); return t ? {k:t.k, l:t.l, c:'T', g:t.g, f:[], gate:t.gate} : null;
  };
  /* her advert's title and words are about her sport and her area -- the door tile and the sport group are only the way in */
  var _dtT=T.draftTitle, _dbT=T.draftBody;
  T.draftTitle=function(pk){
    if(!trnOn()) return _dtT(pk);
    var r=null, w=null;
    for(var i=pk.length-1;i>=0;i--){ if(!r && pk[i].key==='what') r=pk[i]; if(!w && pk[i].key==='where') w=pk[i]; }
    return (r ? r.label : 'Sport & fitness')+' \u2014 '+(w ? w.label : LOC.suburb);
  };
  T.draftBody=function(pk){ return _dbT(trnOn() ? pk.filter(function(p){ return p.key!=='tdoor' && p.key!=='group'; }) : pk); };
  /* what the advert IS: Tutors / Trainers (CASUALS-IS-SERVICES-1 pattern) */
  var _coT=catOut;
  catOut=function(c){ if(c && c.key==='tutors' && trnOn()) return {category:'Tutors', service_class:'Trainers'}; return _coT(c); };
  var _hpT=handoverPayload;
  handoverPayload=function(){
    var r=_hpT();
    try{ if(trnOn() && r && r.body){ var w=pickOf('what');
      r.body.category='Tutors'; r.body.service_class='Trainers';
      if(w){ r.body.subject=w.label; r.body.service_type=w.label; } } }catch(e){}
    return r;
  };
  /* a trainer is not asked a school level or online/in person, so those are not counted against her listing score */
  var _lsT=lsOf;
  lsOf=function(pk, ph){
    if(!trnOn()) return _lsT(pk, ph);
    var keep=REQ.tutors; REQ.tutors=['subject'];
    try{ return _lsT(pk, ph); } finally { REQ.tutors=keep; }
  };
  /* the AI example's 'I train people in this -- list me free' (and any enrolment link): /quick/?role=<sport> opens her
     sell flow on the price step with the door, group and sport already chosen */
  var m=/[?&]role=([a-z0-9_]+)/.exec(location.search||''), r0=m && trnRole(m[1]);
  if(r0){
    setTimeout(function(){
      ci=TI; start('sell');
      picks.push({label:'Sport & fitness', photo:null, key:'tdoor', trn:1});
      picks.push({label:r0.g, photo:'role_'+r0.k, key:'group', g:r0.g});
      picks.push({label:r0.l, photo:'role_'+r0.k, key:'what', r:r0.k});
      step=3; drawStep();
    },0);
  }
})();
</script>
"""


def main():
    q = io.open(QH, encoding="utf-8").read()
    if MARK in q:
        sys.exit("already applied (%s in quick.html)" % MARK)
    if "QUICK-TRAINERS:BEGIN" not in q:
        sys.exit("quick.html has no QUICK-TRAINERS block -- run scripts/sync_quick_roles.py first")
    reps = [
        ("    car:   {t:'Per car',",
         "    session:{t:'Per session',        u:' / session',  x:0},   /* TRAINERS-DOOR-1 (RUL-217(c)): coaching has no wage floor */\n"
         "    month: {t:'Per month',           u:' / month',    x:0},\n"
         "    package:{t:'Per package',        u:' / package',  x:0},\n"
         "    car:   {t:'Per car',"),
        ("if(cat().key==='tutors') return {def:'hour', opts:['hour','visit']};",
         "if(cat().key==='tutors' && window.trnOn && trnOn()) return {def:'session', opts:['session','month','package']};   /* TRAINERS-DOOR-1 */\n"
         "    if(cat().key==='tutors') return {def:'hour', opts:['hour','visit']};"),
        ("[/ \\/ month/g,' per maand'],",
         "[/ \\/ month/g,' per maand'],[/ \\/ session/g,' per sessie'],[/ \\/ package/g,' per pakket'],"),
        ("var _gw=pickOf('what'), _gxP=(window.svcIs && svcIs(c) && _gw && _gw.r)\n      ? fetch('/examples/roles?country='",
         "var _gw=pickOf('what'), _gxT=!!(window.trnOn && c.key==='tutors' && trnOn() && _gw && _gw.r),   /* TRAINERS-DOOR-1 */\n"
         "        _gxP=((window.svcIs && svcIs(c) && _gw && _gw.r) || _gxT)\n"
         "      ? fetch((_gxT ? '/examples/trainers?country=' : '/examples/roles?country=')"),
    ]
    for a, b in reps:
        n = q.count(a)
        if n != 1:
            sys.exit("anchor found %d times, expected 1: %r" % (n, a[:70]))
        q = q.replace(a, b)
    end = q.rfind("</body>")
    assert end > 0 and q.count("</body>") == 1
    q = q[:end] + DOOR_JS + q[end:]
    ts = time.strftime("%Y%m%d-%H%M%S")
    shutil.copyfile(QH, QH + ".bak-trainers-%s" % ts)
    shutil.copyfile(HARN, HARN + ".bak-trainers-%s" % ts)
    io.open(QH, "w", encoding="utf-8").write(q)
    shutil.copyfile(QH, HARN)
    print("quick.html + genie/HARNESS.html: Trainers door applied (%d bytes)" % len(q.encode("utf-8")))


if __name__ == "__main__":
    main()
