#!/usr/bin/env python3
"""COUNTRY-PACK-1 (David 25 Sep 2026: "we need to while we have this fixed also fix the other countries for these
fixes"). Quick learns WHERE she is -- country (?cc=, Cloudflare's country header via /quick/me, the phone's time
zone) and city (?city=, her account, Cloudflare's city header, or one tap) -- and every example follows: that
city's areas, money in that currency with bands that fit it, trip destinations of that country, and example names
from one local naming tradition. Before this every visitor, in every country and every ZA city except Pretoria,
was shown Pretoria suburbs and Rands.
The pack is data (roles/quick_country_packs.json), injected between QUICK-COUNTRY markers; the runtime block is
appended once. Idempotent; asserts every anchor."""
import io, json, os
R = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
def rd(p): return io.open(os.path.join(R, p), encoding="utf-8").read()
def wr(p, s):
    io.open(os.path.join(R, p), "w", encoding="utf-8").write(s); assert rd(p) == s, p
def rep(s, a, b, name):
    if b in s: return s
    assert s.count(a) == 1, "anchor %s: %d" % (name, s.count(a)); return s.replace(a, b)
q = rd("quick.html")
# 1. generic money parsing / printing
q = rep(q, "  var nums=(label.match(/R\\s?[\\d][\\d\\s.]*[km]?/gi)||[]).map(numOf)",
           "  var nums=(label.match(/(?:N\\$|A\\$|KSh|MT|R|P|\\u00a3|\\u20ac|\\$)\\s?[\\d][\\d\\s.,]*[km]?/gi)||[]).map(numOf)", "bandOf")
q = rep(q, "  var m=String(tok).replace(/\\s/g,'').match(/([\\d.]+)\\s*([km])?/i);",
           "  var m=String(tok).replace(/[\\s,]/g,'').match(/([\\d.]+)\\s*([km])?/i);", "numOf")
# 2. the rate screen takes the same country
q = rep(q, "  function country(){\n    var m=/[?&]cc=([a-z]{2})\\b/i.exec(location.search||'');",
           "  function country(){\n    if(window.QCC && MINW[window.QCC==='GB'?'UK':window.QCC]) return window.QCC==='GB'?'UK':window.QCC;   /* COUNTRY-PACK-1: one country for the whole door */\n    var m=/[?&]cc=([a-z]{2})\\b/i.exec(location.search||'');", "rate country")
# 3. destinations consult the country pack
q = rep(q, "    var w=pickOf('what'), list=(w && DEST[w.label]) || MIX;",
           "    var w=pickOf('what'), list=(window.QDEST_LIST && window.QDEST_LIST(w)) || (w && DEST[w.label]) || MIX;", "dest list")
q = rep(q, "      var pics=list.every(function(n){ return !!DEST_PIC[n]; });",
           "      var XP=window.QDEST_PICS||{}; var pics=list.every(function(n){ return !!(DEST_PIC[n]||XP[n]); });", "dest pics")
q = rep(q, "tiles:list.map(function(n){ return {t:n, p:DEST_PIC[n]}; })",
           "tiles:list.map(function(n){ return {t:n, p:DEST_PIC[n]||XP[n]}; })", "dest tiles")
# 4. the pack data + runtime
pack = json.loads(rd("roles/quick_country_packs.json"))
data = ("/* QUICK-COUNTRY:BEGIN -- generated by scripts/apply_country_pack.py from roles/quick_country_packs.json; do not edit */\n"
        "var QPACK = %s;\n/* QUICK-COUNTRY:END */" % json.dumps(pack, ensure_ascii=False))
import re
if "/* QUICK-COUNTRY:BEGIN" in q:
    q = re.sub(r"/\* QUICK-COUNTRY:BEGIN.*?/\* QUICK-COUNTRY:END \*/", lambda m: data, q, flags=re.S)
BLOCK = r"""
/* ===========================================================================
   COUNTRY-PACK-1 (David 25 Sep 2026: "fix the other countries for these fixes"). WHERE she is decides the
   examples: her city's areas, her currency and price bands, her country's trip destinations, local names.
   Country: ?cc= > Cloudflare's country (via /quick/me) > the phone's time zone > South Africa.
   City: ?city= > her account > Cloudflare's city > what she chose before on this phone > ONE tap.
   Languages are untouched (RUL-165: only ZA's languages are offered; English everywhere).
   ------------------------------------------------------------------------- */
__DATA__
(function(){
  var ZA=QPACK.ZA, ORIG=null, userCC=false, userCity=false;
  var FX={ZA:1,NA:1,BW:0.75,MZ:3.5,KE:7,GB:0.042,DE:0.05,AU:0.085,US:0.055};
  var FB0=JSON.parse(JSON.stringify(FALLBACK_BAND));
  function tzCC(){ try{ var tz=Intl.DateTimeFormat().resolvedOptions().timeZone||'';
      for(var cc in QPACK){ var z=QPACK[cc].tz||[]; for(var i=0;i<z.length;i++) if(tz===z[i] || (z[i].slice(-1)==='/' && tz.indexOf(z[i])===0)) return cc; }
      if(/^America\//.test(tz)) return 'US'; }catch(e){} return null; }
  function lsGet(k){ try{ return localStorage.getItem(k); }catch(e){ return null; } }
  function lsSet(k,v){ try{ localStorage.setItem(k,v); }catch(e){} }
  var m=/[?&]cc=([a-z]{2})\b/i.exec(location.search||''), cc=m?m[1].toUpperCase():null;
  if(cc==='UK') cc='GB';
  if(cc && QPACK[cc]) userCC=true; else cc=tzCC()||'ZA';
  function slug(n){ return String(n).normalize('NFKD').replace(/[̀-ͯ]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,''); }
  function snapshot(){ if(ORIG) return; ORIG={};
    CATS.forEach(function(c){ ['sell','find'].forEach(function(side){ ((c[side]||{}).steps||[]).forEach(function(s,i){
      if(s.key==='price') ORIG[c.key+'|'+side+'|'+i]=s.tiles.map(function(t){ return t.t; }); }); }); }); }
  function applyBands(P){
    snapshot();
    CATS.forEach(function(c){ ['sell','find'].forEach(function(side){ ((c[side]||{}).steps||[]).forEach(function(s,i){
      var o=ORIG[c.key+'|'+side+'|'+i]; if(!o) return;
      var b=(P.bands||{})[c.key], j=0;
      s.tiles.forEach(function(t,k){ var base=o[k];
        if(b && /\d/.test(base) && !/quote|ask/i.test(base)) t.t=b[j++]||base; else t.t=base; }); }); }); });
  }
  var QP=ZA;
  window.QCC='ZA'; window.QCITY=null;
  window.QDEST_PICS={};
  function setCity(city, remember){
    if(!QP.cities[city]) return false;
    window.QCITY=city; LOC.city=city; LOC.suburb=QP.cities[city][0];
    NEARBY.length=0; QP.cities[city].slice(1).forEach(function(a){ NEARBY.push(a); });
    FURTHER.length=0; Object.keys(QP.cities).filter(function(x){ return x!==city; }).slice(0,5).forEach(function(x){ FURTHER.push(x); });
    if(!FURTHER.length) QP.cities[city].slice(3).forEach(function(a){ FURTHER.push(a); });
    if(remember) lsSet('ts_qcity', QCC+'|'+city);
    return true;
  }
  function applyPack(c){
    QP=QPACK[c]||ZA; window.QCC=QPACK[c]?c:'ZA'; window.QP=QP;
    applyBands(QP);
    var fx=FX[QCC]||1; Object.keys(FB0).forEach(function(k){ FALLBACK_BAND[k]=[Math.round(FB0[k][0]*fx), Math.round(FB0[k][1]*fx)]; });
    window.QDEST_PICS={};
    if(QP.dest){ var seen={}; ['lodge','tour','drive','rail','fish'].forEach(function(k){ QP.dest[k].forEach(function(n){
        if(seen[n]) return; seen[n]=1; var key='dest_'+QCC.toLowerCase()+'_'+slug(n); PH[key]=PH_BASE+key+'.jpg';
        var im=new Image(); im.onload=function(){ window.QDEST_PICS[n]=key; }; im.src=PH[key]; }); }); }
    var saved=(lsGet('ts_qcity')||'').split('|');
    var mc=/[?&]city=([^&]+)/i.exec(location.search||''), want=mc?decodeURIComponent(mc[1].replace(/\+/g,' ')):null;
    window.QCITY=null;
    if(want && setCity(want,true)) userCity=true;
    else if(saved[0]===QCC && setCity(saved[1],false)) {}
    else if(Object.keys(QP.cities).length===1) setCity(Object.keys(QP.cities)[0],false);   /* one live city: nothing to ask */
    else if(QCC==='ZA'){ LOC.city='Pretoria'; LOC.suburb='Menlyn'; }
    else { LOC.city=QP['default']; LOC.suburb=QP.cities[QP['default']][0]; }
  }
  applyPack(cc);
  window.QUICK_APPLY_PACK=applyPack; window.QUICK_SET_CITY=setCity;
  money=function(v){ v=Math.round(v); var s=QP.cur||'R';
    if(v>=1000000) return s+(Math.round(v/10000)/100).toFixed(2).replace(/\.?0+$/,'')+'m';
    return s+String(v).replace(/\B(?=(\d{3})+(?!\d))/g, (QCC==='GB'||QCC==='US'||QCC==='AU'||QCC==='DE')?',':' '); };
  /* trip destinations of her country (ZA keeps DEST-WHERE-1's own lists) */
  var KIND={'Game lodge':'lodge','Safari':'lodge','Guided tour':'tour','Self-drive':'drive','Rail journey':'rail','Fishing':'fish'};
  window.QDEST_LIST=function(w){ if(QCC==='ZA' || !QP.dest) return null;
    var k=w && KIND[w.label]; if(k) return QP.dest[k];
    return [QP.dest.lodge[0],QP.dest.tour[0],QP.dest.drive[0],QP.dest.lodge[1],QP.dest.tour[1],QP.dest.drive[1]]; };
  /* words and names */
  function loc(s){ s=String(s||''); var area=(QCITY && QP.cities[QCITY]) ? QP.cities[QCITY][0] : LOC.suburb;
    if(QCITY!=='Pretoria') s=s.replace(/Menlyn/g, area);
    var sw=QP.swap||{}; Object.keys(sw).forEach(function(k){ s=s.split(k).join(sw[k]); });
    if(QCC!=='ZA' && QP.dest) s=s.replace(/Clarens/g, QP.dest.lodge[0]).replace(/the taxi is stuck at Solomon Mahlangu/g,'the bus is stuck in traffic');
    return s; }
  window.QLOC=loc;
  if(typeof tradersFor==='function'){ var _tf=tradersFor; tradersFor=function(){ var r=_tf();
      var names=(QCC!=='ZA' && QP.names) ? QP.names : null;
      r.ph=loc(r.ph); r.list=r.list.map(function(t,i){ return {name:names?names[i%names.length]:t.name, last:loc(t.last)}; }); return r; }; }
  function localNames(){ if(QCC==='ZA' || !QP.names) return;
    var ks=Object.keys(COMMS), N=QP.names;
    ks.forEach(function(k,i){ var c=COMMS[k]; c.a=N[(2*i)%N.length]; c.b=N[(2*i+1)%N.length];
      ['bRole','sample','card','sellCard','met','note'].forEach(function(f){ if(c[f]) c[f]=loc(c[f]); }); });
    VOUCH.from=N[0]; }
  localNames();
  /* WHERE: her city's areas; no city yet = one tap to choose it */
  var _flC=flow;
  flow=function(){ var f=_flC(); if(!f || !f.steps || cat().key==='adventures') return f;
    return {steps:f.steps.map(function(s){
      if(!s || s.key!=='where' || !QCITY || (QCC==='ZA' && QCITY==='Pretoria')) return s;
      return {q:s.q, key:'where', kind:'chip', free:s.free, freeHint:s.freeHint, tiles:QP.cities[QCITY].map(function(a){ return {t:a}; })};
    })}; };
  function drawCityPick(){
    setNav();
    var list=Object.keys(QP.cities);
    $('screen').className='screen'; $('screen').setAttribute('data-step','city');
    $('screen').innerHTML='<div class="q">Which city?</div><div class="body mid"><div class="chips">'
      +list.map(function(c,i){ return '<button class="chip" data-c="'+i+'" style="animation-delay:'+(i*30)+'ms">'+c+'</button>'; }).join('')
      +'</div><div class="bznote" style="margin-top:14px">We ask once. This phone remembers it.</div></div>';
    var b=$('screen').querySelectorAll('[data-c]');
    for(var i=0;i<b.length;i++) b[i].onclick=function(){ taps++; setCity(list[+this.getAttribute('data-c')], true); drawStep(); };
    try{ qTranslate($('screen')); }catch(e){}
  }
  var _dsC=drawStep;
  drawStep=function(){
    var s=null; try{ s=flow().steps[step]; }catch(e){}
    var isWhere = s && s.key==='where' && cat().key!=='adventures';
    if(isWhere && !QCITY && mode){ drawCityPick(); return; }
    _dsC();
    if(isWhere && QCITY && Object.keys(QP.cities).length>1){
      var body=$('screen').querySelector('.body');
      if(body && !$('qchcity')){ var a=document.createElement('button'); a.id='qchcity'; a.className='ar-again'; a.type='button';
        a.style.cssText='display:block;margin:12px auto 0'; a.textContent='Not in '+QCITY+'? Change city';
        a.onclick=function(){ window.QCITY=null; drawStep(); }; body.appendChild(a); }
    }
  };
  /* the server's view of where she is: account city, Cloudflare country/city */
  var _mf=window.fetch;
  try{ _mf(location.origin+'/quick/me',{credentials:'include'}).then(function(r){ return r.ok?r.json():null; }).then(function(d){
    if(!d) return; var g=d.geo||{}, gc=String(g.country||'').toUpperCase(); if(gc==='UK') gc='GB';
    if(!userCC && QPACK[gc] && gc!==QCC && !mode){ applyPack(gc); localNames(); }
    if(!userCity && !QCITY){ if(d.city && setCity(d.city,false)) return; if(g.city) setCity(g.city,false); }
  }).catch(function(){}); }catch(e){}
})();
"""
if "COUNTRY-PACK-1 (David 25 Sep 2026" not in q:
    q = rep(q, "\ndrawDoor();\n</script>", BLOCK.replace("__DATA__", data) + "\ndrawDoor();\n</script>", "tail")
wr("quick.html", q)

b = rd("bea_main.py")
b = rep(b, '@app.get("/quick/me")\ndef quick_me(ts_user: str = Cookie(default=None)):\n    em = _session_email(ts_user)\n    out = {"signed_in": False,',
           '@app.get("/quick/me")\ndef quick_me(request: Request, ts_user: str = Cookie(default=None)):\n    em = _session_email(ts_user)\n'
           '    # COUNTRY-PACK-1 (25 Sep 2026): where the visitor is, as Cloudflare already tells us -- country (and city when\n'
           '    # Cloudflare adds it). Read-only, never stored; Quick uses it only to pick which examples to show.\n'
           '    _geo = {"country": (request.headers.get("cf-ipcountry") or "").upper()[:2] or None,\n'
           '            "city": (request.headers.get("cf-ipcity") or "")[:60] or None}\n'
           '    out = {"geo": _geo, "signed_in": False,', "quick_me")
wr("bea_main.py", b)
print("COUNTRY-PACK-1 applied")
