"""build_help.py -- HELP-STORIES-1 (29 Sep 2026): the story guides at trustsquare.co/help/.

David, 29 Sep 2026: "complete the Story file/folder/gallery with its links. But it need to be all live
and reside on the server not the local computer."

Source of truth, all in the repo:
  stories/<type>.json            one story per listing type (steps, chapters, en/af text, pass flags)
  stories/img/<type>/<key>.jpg   the screens a story points at (step.img). NOT in git: the repo's rule is
                                 that media never enters it (.gitignore, scale-shape invariant #4). They go
                                 straight to the server with --push-images and live there.
  stories/help.html              the ONE page that renders any story      -> /help/<type>
  stories/index.html             the gallery of every story                -> /help/
This script writes stories/gallery.json (-> /help/data/index.json) and the generated block of
ops/autodeploy/deploy_manifest.txt, so a new story ships by adding its JSON + screens and running this.
nginx serves /help/ from /var/www/marketsquare/help (short cache, noindex) -- see the server's
sites-enabled/marketsquare, 'HELP-STORIES-1'.

  python3 scripts/build_help.py          # validate, write gallery.json + manifest block
  python3 scripts/build_help.py --check  # validate only; exit 1 if anything is stale or broken
  python3 scripts/build_help.py --push-images   # copy new or changed screens to the server (never deletes)
"""
import hashlib, json, os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ST = os.path.join(ROOT, "stories")
MANIFEST = os.path.join(ROOT, "ops", "autodeploy", "deploy_manifest.txt")
BEGIN = "# ── HELP-STORIES-1: story guides at /help/ (generated by scripts/build_help.py -- do not edit by hand) ──"
END = "# ── end HELP-STORIES-1 ──"
TYPE_RE = re.compile(r"^[a-z0-9_]+$")
OPTIONAL_LANGS = ("zu", "xh", "nso")   # HELP-LANG-1: Quick's other languages; [[Button]] = the app's own words, quoted
SERVER = "root@178.104.73.239"
REMOTE_IMG = "/var/www/marketsquare/help/img"


def load_stories():
    out, errs = [], []
    for fn in sorted(os.listdir(ST)):
        if not fn.endswith(".json") or fn == "gallery.json":
            continue
        t = fn[:-5]
        try:
            d = json.load(open(os.path.join(ST, fn), encoding="utf-8"))
        except Exception as e:
            errs.append("%s: not valid JSON (%s)" % (fn, e)); continue
        if not TYPE_RE.match(t) or d.get("type") != t:
            errs.append("%s: 'type' must equal the file name and be a-z0-9_" % fn)
        for k in ("label", "title", "walked_on", "chapters", "steps"):
            if k not in d:
                errs.append("%s: missing '%s'" % (fn, k))
        steps = [s for s in d.get("steps", []) if s.get("pass")]
        if not steps:
            errs.append("%s: no step passed on the live site -- nothing to show" % fn)
        ns = [s.get("n") for s in d.get("steps", [])]
        if len(ns) != len(set(ns)):
            errs.append("%s: step numbers repeat" % fn)
        chs = set(c.get("id") for c in d.get("chapters", []))
        for s in steps:
            if s.get("ch") not in chs:
                errs.append("%s step %s: chapter %r is not in chapters" % (fn, s.get("n"), s.get("ch")))
            for lg in ("en", "af") + OPTIONAL_LANGS:
                if lg not in ("en", "af") and lg not in s:
                    continue          # HELP-LANG-1: a missing local language falls back to English on the page
                if not (isinstance(s.get(lg), list) and len(s[lg]) == 2 and all(s[lg])):
                    errs.append("%s step %s: '%s' needs [title, text]" % (fn, s.get("n"), lg))
                elif any(t.count("[[") != t.count("]]") for t in s[lg]):
                    errs.append("%s step %s: '%s' has an unclosed [[button]] quote" % (fn, s.get("n"), lg))
            if not os.path.isfile(os.path.join(ST, "img", t, "%s.jpg" % s.get("img"))):
                errs.append("%s step %s: screen stories/img/%s/%s.jpg is missing" % (fn, s.get("n"), t, s.get("img")))
        out.append((t, d, steps))
    return out, errs


def gallery(stories):
    return {"generated_by": "scripts/build_help.py",
            "stories": [{"type": t, "status": d.get("status", "draft"), "flow": d.get("flow"),
                         "label": d["label"], "title": d["title"], "walked_on": d["walked_on"],
                         "steps": len(steps), "cover": steps[0]["img"]}
                        for t, d, steps in stories]}


def manifest_block(stories):
    lines = [BEGIN,
             "stories/help.html          | help/story.html",
             "stories/index.html         | help/index.html",
             "stories/gallery.json       | help/data/index.json"]
    for t, d, steps in stories:
        lines.append("stories/%s.json | help/data/%s.json" % (t, t))
    lines.append(END)
    return "\n".join(lines) + "\n"


def _run(cmd):
    return subprocess.run(cmd, capture_output=True, text=True, timeout=300)


def push_images(stories):
    """New or changed screens -> the server. Compares md5s first; never deletes anything there."""
    loader = os.path.join(ROOT, "load_sandbox_ssh.sh")        # SSH-BOOTSTRAP-1, as backup_db_sandbox.py
    if os.path.isfile(loader):
        _run(["bash", loader])
    sent = 0
    for t, d, steps in stories:
        local = {}
        for k in sorted(set(s["img"] for s in steps)):
            f = os.path.join(ST, "img", t, k + ".jpg")
            local[k + ".jpg"] = hashlib.md5(open(f, "rb").read()).hexdigest()
        r = _run(["ssh", "-o", "ConnectTimeout=20", SERVER,
                  "mkdir -p %s/%s && cd %s/%s && (md5sum *.jpg 2>/dev/null || true)" % (REMOTE_IMG, t, REMOTE_IMG, t)])
        if r.returncode != 0:
            sys.exit("FAIL  server unreachable: %s" % (r.stderr or r.stdout).strip()[:300])
        remote = dict((ln.split()[1], ln.split()[0]) for ln in r.stdout.splitlines() if len(ln.split()) == 2)
        todo = [fn for fn, h in local.items() if remote.get(fn) != h]
        if todo:
            r = _run(["scp", "-o", "ConnectTimeout=20"] + [os.path.join(ST, "img", t, fn) for fn in todo]
                     + ["%s:%s/%s/" % (SERVER, REMOTE_IMG, t)])
            if r.returncode != 0:
                sys.exit("FAIL  scp %s: %s" % (t, (r.stderr or r.stdout).strip()[:300]))
        # a file copied from Windows arrives rwx------ and nginx answers 403 -- make every screen world-readable
        _run(["ssh", "-o", "ConnectTimeout=20", SERVER,
              "chmod 755 %s %s/%s && chmod 644 %s/%s/*.jpg" % (REMOTE_IMG, REMOTE_IMG, t, REMOTE_IMG, t)])
        sent += len(todo)
        print("%-24s %d screen(s), %d sent" % (t, len(local), len(todo)))
    print("pushed %d screen(s)" % sent)


def main():
    check = "--check" in sys.argv
    if "--push-images" in sys.argv:
        stories, errs = load_stories()
        for e in errs:
            print("ERROR  " + e)
        if errs:
            sys.exit("not pushed: fix the errors above first")
        push_images(stories); return
    stories, errs = load_stories()
    g = json.dumps(gallery(stories), ensure_ascii=False, indent=1) + "\n"
    gp = os.path.join(ST, "gallery.json")
    cur_g = open(gp, encoding="utf-8").read() if os.path.isfile(gp) else ""
    man = open(MANIFEST, encoding="utf-8").read()
    blk = manifest_block(stories)
    if BEGIN in man and END in man:
        i = man.index(BEGIN); j = man.index(END) + len(END) + 1
        new_man = man[:i] + blk + man[j:]
    else:
        new_man = man.rstrip("\n") + "\n\n" + blk
    stale = []
    if cur_g != g:
        stale.append("stories/gallery.json")
    if new_man != man:
        stale.append("deploy_manifest.txt HELP-STORIES-1 block")
    for e in errs:
        print("ERROR  " + e)
    if check:
        for s in stale:
            print("STALE  " + s + " -- run python3 scripts/build_help.py")
        print("%d stor%s, %d error(s), %d stale" % (len(stories), "y" if len(stories) == 1 else "ies", len(errs), len(stale)))
        sys.exit(1 if (errs or stale) else 0)
    if errs:
        sys.exit("not written: fix the errors above first")
    open(gp, "w", encoding="utf-8").write(g)
    open(MANIFEST, "w", encoding="utf-8", newline="\n").write(new_man)
    print("wrote gallery.json (%d stor%s) and the manifest block (%d lines)"
          % (len(stories), "y" if len(stories) == 1 else "ies", blk.count("\n") - 2))


if __name__ == "__main__":
    main()
