"""build_help.py -- HELP-STORIES-1 (29 Sep 2026): the story guides at trustsquare.co/help/.

David, 29 Sep 2026: "complete the Story file/folder/gallery with its links. But it need to be all live
and reside on the server not the local computer."

Source of truth, all in the repo:
  stories/<type>.json            one story per listing type (steps, chapters, en/af text, pass flags)
  stories/img/<type>/<key>.jpg   the screens a story points at (step.img). NOT in git: the repo's rule is
                                 that media never enters it (.gitignore, scale-shape invariant #4). They go
                                 straight to the server with --push-images and live there.
  stories/help.html              the ONE page that renders any story      -> /help/<type>
  stories/index.html             the gallery of every story                -> /help/
This script writes stories/gallery.json (-> /help/data/index.json) and the generated block of
ops/autodeploy/deploy_manifest.txt, so a new story ships by adding its JSON + screens and running this.
nginx serves /help/ from /var/www/marketsquare/help (short cache, noindex) -- see the server's
sites-enabled/marketsquare, 'HELP-STORIES-1'.

  python3 scripts/build_help.py          # validate, write gallery.json + manifest block
  python3 scripts/build_help.py --check  # validate only; exit 1 if anything is stale or broken
  python3 scripts/build_help.py --push-images   # copy new or changed screens to the server (never deletes)
  python3 scripts/build_help.py --pull-images   # copy screens the laptop lacks FROM the server (never deletes or overwrites)

HELP-PULL-1 (3 Oct 2026): the server is where the screens live -- cloud story walks put theirs there through
/qa/help-image and the laptop never saw them, so on 3 Oct --check read 235 'missing' screens that were all
live. --check on the laptop now pulls whatever it lacks from the server first (rsync --ignore-existing: it
never deletes or overwrites a local file), then judges. A screen missing on the server too still fails.
"""
import hashlib, json, os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ST = os.path.join(ROOT, "stories")
MANIFEST = os.path.join(ROOT, "ops", "autodeploy", "deploy_manifest.txt")
BEGIN = "# ── HELP-STORIES-1: story guides at /help/ (generated by scripts/build_help.py -- do not edit by hand) ──"
END = "# ── end HELP-STORIES-1 ──"
TYPE_RE = re.compile(r"^[a-z0-9_]+$")
SERVE_RE = re.compile(r"^[a-z0-9_]+\*?$")   # HOW-NEAREST-1: a listing type, or a whole door ('cars_*')
DOORS = ("property", "cars", "tutors", "collectors", "adventures", "localmarket")   # Quick's doors; a role guide is 'services'
OPTIONAL_LANGS = ("zu", "xh", "nso")   # HELP-LANG-1: Quick's other languages; [[Button]] = the app's own words, quoted
SERVER = "root@178.104.73.239"
REMOTE_IMG = "/var/www/marketsquare/help/img"
# QA-CLOUD-1: the server's cloud-ship gate checks the screens where /qa/help-image put them (the clone has none)
IMG_ROOT = os.environ.get("TS_HELP_IMG") or os.path.join(ST, "img")


def load_stories():
    out, errs = [], []
    for fn in sorted(os.listdir(ST)):
        if not fn.endswith(".json") or fn == "gallery.json":
            continue
        t = fn[:-5]
        try:
            d = json.load(open(os.path.join(ST, fn), encoding="utf-8"))
        except Exception as e:
            errs.append("%s: not valid JSON (%s)" % (fn, e)); continue
        if not TYPE_RE.match(t) or d.get("type") != t:
            errs.append("%s: 'type' must equal the file name and be a-z0-9_" % fn)
        for k in ("label", "title", "walked_on", "chapters", "steps"):
            if k not in d:
                errs.append("%s: missing '%s'" % (fn, k))
        steps = [s for s in d.get("steps", []) if s.get("pass")]
        if not steps:
            errs.append("%s: no step passed on the live site -- nothing to show" % fn)
        ns = [s.get("n") for s in d.get("steps", [])]
        if len(ns) != len(set(ns)):
            errs.append("%s: step numbers repeat" % fn)
        chs = set(c.get("id") for c in d.get("chapters", []))
        for s in steps:
            if s.get("ch") not in chs:
                errs.append("%s step %s: chapter %r is not in chapters" % (fn, s.get("n"), s.get("ch")))
            for lg in ("en", "af") + OPTIONAL_LANGS:
                if lg not in ("en", "af") and lg not in s:
                    continue          # HELP-LANG-1: a missing local language falls back to English on the page
                if not (isinstance(s.get(lg), list) and len(s[lg]) == 2 and all(s[lg])):
                    errs.append("%s step %s: '%s' needs [title, text]" % (fn, s.get("n"), lg))
                elif any(t.count("[[") != t.count("]]") for t in s[lg]):
                    errs.append("%s step %s: '%s' has an unclosed [[button]] quote" % (fn, s.get("n"), lg))
            if s.get("cost", "free") not in ("free", "1T", "1T_check", "1T_accept") \
                    and not re.match(r"^[1-9]T_report$", str(s.get("cost"))):   # STORY-REPORT-COST-1: 3T dossier, 5T report
                errs.append("%s step %s: cost must be free, 1T, 1T_check, 1T_accept or <n>T_report" % (fn, s.get("n")))
            if not os.path.isfile(os.path.join(IMG_ROOT, t, "%s.jpg" % s.get("img"))):
                errs.append("%s step %s: screen stories/img/%s/%s.jpg is missing" % (fn, s.get("n"), t, s.get("img")))
        # HOW-NEAREST-1 (1 Oct 2026): 'serves' lists the other listing types the guide itself says follow the same steps
        # (its step 2: "Car, bakkie, SUV or bike", "Caregivers, au pairs and creche assistants ..."); 'deal' (sale | let)
        # keeps a house TO LET off the house-FOR-SALE guide. Quick's How opens the nearest guide by these.
        sv = d.get("serves", [])
        if not isinstance(sv, list) or not all(isinstance(x, str) and SERVE_RE.match(x) for x in sv):
            errs.append("%s: 'serves' must be a list of listing types (a-z0-9_, or a door ending in *)" % fn)
        if d.get("deal") not in (None, "sale", "let"):
            errs.append("%s: 'deal' must be sale or let" % fn)
        # HOW-GATE-F4 (1 Oct 2026): a gate note promises a gate step -- with no passed step marked gate the banner never
        # shows (the electrician guide's licence gate was invisible), and a note naming another step sends her to the wrong one
        if d.get("gate_note"):
            g = [s for s in steps if s.get("gate")]
            if not g:
                errs.append("%s: has a gate_note but no passed step has \"gate\": true -- the gate banner never shows" % fn)
            else:
                for lg, txt in d["gate_note"].items():
                    if str(g[0].get("n")) not in re.findall(r"\d+", txt):
                        errs.append("%s: gate_note '%s' does not name step %s, the gate step" % (fn, lg, g[0].get("n")))
        out.append((t, d, steps))
    seen = {}
    for t, d, steps in out:                       # one listing type, one deal -> one guide, never a coin toss
        for x in d.get("serves", []) if isinstance(d.get("serves"), list) else []:
            for deal in ([d["deal"]] if d.get("deal") else ["sale", "let"]):
                k = (x, deal)
                if k in seen and seen[k] != t:
                    errs.append("%s.json: serves %r (%s), which %s.json serves too" % (t, x, deal, seen[k]))
                seen[k] = t
    return out, errs


def door_of(t):
    p = t.split("_")[0]
    return p if p in DOORS else "services"


def gallery(stories):
    return {"generated_by": "scripts/build_help.py",
            "stories": [dict({"type": t, "status": d.get("status", "draft"), "flow": d.get("flow"),
                              "label": d["label"], "title": d["title"], "walked_on": d["walked_on"],
                              "steps": len(steps), "cover": steps[0]["img"],
                              # HOW-NEAREST-1: what Quick's How needs to pick the nearest guide -- the door, whether the
                              # guide was walked in Quick at all (a guide walked in TrustSquare's Sell has no Quick card),
                              # and the types / deal it serves
                              "door": door_of(t), "quick": any(s.get("quick") for s in steps)},
                             **{k: d[k] for k in ("serves", "deal", "derived_from") if d.get(k)})   # ROLE-GUIDES-1
                        for t, d, steps in stories]}


def manifest_block(stories):
    lines = [BEGIN,
             "stories/help.html          | help/story.html",
             "stories/index.html         | help/index.html",
             "stories/gallery.json       | help/data/index.json"]
    for t, d, steps in stories:
        lines.append("stories/%s.json | help/data/%s.json" % (t, t))
    lines.append(END)
    return "\n".join(lines) + "\n"


def _run(cmd):
    return subprocess.run(cmd, capture_output=True, text=True, timeout=300)


def push_images(stories):
    """New or changed screens -> the server. Compares md5s first; never deletes anything there."""
    loader = os.path.join(ROOT, "load_sandbox_ssh.sh")        # SSH-BOOTSTRAP-1, as backup_db_sandbox.py
    if os.path.isfile(loader):
        _run(["bash", loader])
    sent = 0
    for t, d, steps in stories:
        local = {}
        for k in sorted(set(s["img"] for s in steps)):
            f = os.path.join(ST, "img", t, k + ".jpg")
            local[k + ".jpg"] = hashlib.md5(open(f, "rb").read()).hexdigest()
        r = _run(["ssh", "-o", "ConnectTimeout=20", SERVER,
                  "mkdir -p %s/%s && cd %s/%s && (md5sum *.jpg 2>/dev/null || true)" % (REMOTE_IMG, t, REMOTE_IMG, t)])
        if r.returncode != 0:
            sys.exit("FAIL  server unreachable: %s" % (r.stderr or r.stdout).strip()[:300])
        remote = dict((ln.split()[1], ln.split()[0]) for ln in r.stdout.splitlines() if len(ln.split()) == 2)
        todo = [fn for fn, h in local.items() if remote.get(fn) != h]
        if todo:
            r = _run(["scp", "-o", "ConnectTimeout=20"] + [os.path.join(ST, "img", t, fn) for fn in todo]
                     + ["%s:%s/%s/" % (SERVER, REMOTE_IMG, t)])
            if r.returncode != 0:
                sys.exit("FAIL  scp %s: %s" % (t, (r.stderr or r.stdout).strip()[:300]))
        # a file copied from Windows arrives rwx------ and nginx answers 403 -- make every screen world-readable
        _run(["ssh", "-o", "ConnectTimeout=20", SERVER,
              "chmod 755 %s %s/%s && chmod 644 %s/%s/*.jpg" % (REMOTE_IMG, REMOTE_IMG, t, REMOTE_IMG, t)])
        sent += len(todo)
        print("%-24s %d screen(s), %d sent" % (t, len(local), len(todo)))
    print("pushed %d screen(s)" % sent)


def pull_images():
    """HELP-PULL-1: screens the laptop lacks <- the server. Never deletes, never overwrites. Returns a short note."""
    if os.environ.get("TS_HELP_IMG"):
        return "pull skipped: TS_HELP_IMG points at the screens (the server's own gate)"
    loader = os.path.join(ROOT, "load_sandbox_ssh.sh")
    if os.path.isfile(loader):
        try:
            _run(["bash", loader])
        except Exception:
            pass
    os.makedirs(IMG_ROOT, exist_ok=True)
    try:
        r = _run(["rsync", "-a", "--ignore-existing", "--itemize-changes", "-e", "ssh -o ConnectTimeout=15 -o BatchMode=yes",
                  "%s:%s/" % (SERVER, REMOTE_IMG), IMG_ROOT.rstrip("/") + "/"])
    except Exception as e:
        return "pull skipped: %s" % type(e).__name__
    if r.returncode != 0:
        return "pull skipped: server unreachable (%s)" % (r.stderr or r.stdout).strip()[-120:]
    got = sum(1 for ln in r.stdout.splitlines() if ln.startswith(">f"))
    return "pulled %d screen(s) from the server" % got


def main():
    check = "--check" in sys.argv
    if "--pull-images" in sys.argv:
        print(pull_images()); return
    if check and not os.environ.get("TS_HELP_IMG"):
        stories0, errs0 = load_stories()
        if any("is missing" in e for e in errs0):
            print("HELP-PULL-1: " + pull_images())
    if "--push-images" in sys.argv:
        stories, errs = load_stories()
        for e in errs:
            print("ERROR  " + e)
        if errs:
            sys.exit("not pushed: fix the errors above first")
        push_images(stories); return
    stories, errs = load_stories()
    g = json.dumps(gallery(stories), ensure_ascii=False, indent=1) + "\n"
    gp = os.path.join(ST, "gallery.json")
    cur_g = open(gp, encoding="utf-8").read() if os.path.isfile(gp) else ""
    man = open(MANIFEST, encoding="utf-8").read()
    blk = manifest_block(stories)
    if BEGIN in man and END in man:
        i = man.index(BEGIN); j = man.index(END) + len(END) + 1
        new_man = man[:i] + blk + man[j:]
    else:
        new_man = man.rstrip("\n") + "\n\n" + blk
    stale = []
    if cur_g != g:
        stale.append("stories/gallery.json")
    if new_man != man:
        stale.append("deploy_manifest.txt HELP-STORIES-1 block")
    for e in errs:
        print("ERROR  " + e)
    if check:
        for s in stale:
            print("STALE  " + s + " -- run python3 scripts/build_help.py")
        print("%d stor%s, %d error(s), %d stale" % (len(stories), "y" if len(stories) == 1 else "ies", len(errs), len(stale)))
        sys.exit(1 if (errs or stale) else 0)
    if errs:
        sys.exit("not written: fix the errors above first")
    open(gp, "w", encoding="utf-8").write(g)
    open(MANIFEST, "w", encoding="utf-8", newline="\n").write(new_man)
    print("wrote gallery.json (%d stor%s) and the manifest block (%d lines)"
          % (len(stories), "y" if len(stories) == 1 else "ies", blk.count("\n") - 2))


if __name__ == "__main__":
    main()
