# -*- coding: utf-8 -*-
"""Export legal must-have card CONTENT to a phone-friendly JS data file.
Single source of truth: gen_legal_must_haves.py (edit content there, re-run this).
Output: assets/legal-must-haves/legal-cards.js -> window.SF_LEGAL_CARDS
"""
import json, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_legal_must_haves as g

out = {}
for cc, cats in g.CONTENT.items():
    out[cc] = {"name": g.COUNTRY_NAMES[cc].title(), "cats": {}}
    for cat, (rows, foot, note) in cats.items():
        accent = g.STYLE[cat][0]
        label = g.STYLE[cat][3]
        out[cc]["cats"][cat] = {
            "label": label, "title": g.TITLES[cat], "accent": accent,
            "rows": [[r[1], r[2], r[3], r[4]] for r in rows],  # title, sub, action, chip
            "foot": foot, "note": note,
        }
js = "// Generated by scripts/export_legal_cards_js.py — do not hand-edit.\n" \
     "// Content source: scripts/gen_legal_must_haves.py (version 2026-07-17)\n" \
     "window.SF_LEGAL_CARDS = " + json.dumps(out, ensure_ascii=False, separators=(',',':')) + ";\n"
path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "assets", "legal-must-haves", "legal-cards.js")
open(path, "w", encoding="utf-8").write(js)
print("written", os.path.getsize(path)//1024, "KB")
