#!/usr/bin/env python3
"""
i18n_inventory.py -- I18N_READINESS.md item 1 (RUL-075). Built 1 Sep 2026.

READ-ONLY string inventory extractor: walks the served front-end sources and emits
every user-visible (or candidate user-visible) string with its location, so the
extraction job is MEASURED, not guessed, and its growth is tracked during the freeze.

Touches NOTHING the live app serves. Writes only:
  i18n/inventory.json        -- full inventory (unique strings, locations, counts)
  i18n/inventory_trend.csv   -- one appended row per run (the count trend)

Scope (per the readiness plan): marketsquare.html + ms.js, plus the small served
JS assets (ts_fares/ts_report/ts_demo_banner). trip_essentials.js is EXCLUDED on
purpose: it is generated by scripts/build_trip_essentials.py -- localisation of that
content happens at the generator, not in the bundle.

Heuristics, stated honestly:
  html-text / attr:*   -- high confidence user-visible.
  js-html-text         -- text runs inside JS string/template literals that contain
                          markup; high confidence.
  js-literal           -- sentence-like plain JS literals; CANDIDATES needing human
                          triage at Phase A (some are logs/internal).
Run:  python3 scripts/i18n_inventory.py
"""
import csv, datetime, json, re, sys
from html.parser import HTMLParser
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "i18n"

HTML_FILES = ["marketsquare.html"]
JS_FILES = ["ms.js", "ts_fares.js", "ts_report.js", "ts_demo_banner.js"]

TRANSLATABLE_ATTRS = {"placeholder", "title", "aria-label", "alt", "data-tooltip", "data-label"}
NON_UI = re.compile(r"^(https?://|/|\.{0,2}/|#|data:|mailto:)|\.(js|css|png|jpe?g|webp|svg|mp4|json|html)(\?|$)", re.I)

def visible(s):
    t = s.strip()
    if len(t) < 2 or NON_UI.search(t):
        return None
    if not re.search(r"[A-Za-z]{2}", t):          # skip numbers/symbols-only
        return None
    return re.sub(r"\s+", " ", t)

class Walker(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.hidden = None          # inside <script>/<style>
        self.entries = []           # (line, kind, text)
        self.script_chunks = []     # (line, js source) for the JS pass

    def handle_starttag(self, tag, attrs):
        if tag in ("script", "style"):
            self.hidden = tag
        line = self.getpos()[0]
        for k, v in attrs:
            if k in TRANSLATABLE_ATTRS and v:
                t = visible(v)
                if t:
                    self.entries.append((line, "attr:" + k, t))

    def handle_endtag(self, tag):
        if tag == self.hidden:
            self.hidden = None

    def handle_data(self, data):
        if self.hidden == "script":
            self.script_chunks.append((self.getpos()[0], data))
            return
        if self.hidden == "style":
            return
        t = visible(data)
        if t:
            self.entries.append((self.getpos()[0], "html-text", t))

STR_LIT = re.compile(r"'((?:[^'\\\n]|\\.)*)'|\"((?:[^\"\\\n]|\\.)*)\"|`((?:[^`\\]|\\.)*)`", re.S)
TAG_TEXT = re.compile(r">([^<>{}]+?)<")
ATTR_IN_MARKUP = re.compile(r"(placeholder|title|aria-label|alt|data-tooltip)\s*=\s*[\"']([^\"'<>]+)[\"']")
SENTENCEY = re.compile(r"[A-Za-z]{2}.*\s.*[A-Za-z]{2}")   # two words minimum
CSSISH = re.compile(r"[:;].*[:;]|^\s*[\d.]+(px|em|rem|%|vh|vw)\b")

def scan_js(src, base_line=1):
    out = []
    for m in STR_LIT.finditer(src):
        lit = next(g for g in m.groups() if g is not None)
        line = base_line + src.count("\n", 0, m.start())
        if "<" in lit and ">" in lit:                     # markup-bearing literal
            clean = re.sub(r"\$\{[^}]*\}", " ", lit)
            for tm in TAG_TEXT.finditer(clean):
                t = visible(tm.group(1))
                if t:
                    out.append((line, "js-html-text", t))
            for am in ATTR_IN_MARKUP.finditer(clean):
                t = visible(am.group(2))
                if t:
                    out.append((line, "js-html-attr:" + am.group(1), t))
        else:
            t = visible(lit)
            if t and SENTENCEY.search(t) and not CSSISH.search(t):
                out.append((line, "js-literal", t))
    return out

def main():
    inv = {}      # text -> {"kinds": set, "locations": [file:line], "count": n}
    per_file = {}

    def add(fname, items):
        c = {}
        for line, kind, text in items:
            c[kind.split(":")[0]] = c.get(kind.split(":")[0], 0) + 1
            e = inv.setdefault(text, {"kinds": set(), "locations": [], "count": 0})
            e["kinds"].add(kind)
            e["count"] += 1
            if len(e["locations"]) < 20:
                e["locations"].append(f"{fname}:{line}")
        per_file[fname] = c

    for f in HTML_FILES:
        p = ROOT / f
        if not p.exists():
            print(f"[skip] {f} missing"); continue
        w = Walker()
        w.feed(p.read_text(encoding="utf-8", errors="replace"))
        items = list(w.entries)
        for base, chunk in w.script_chunks:
            items += scan_js(chunk, base)
        add(f, items)

    for f in JS_FILES:
        p = ROOT / f
        if not p.exists():
            print(f"[skip] {f} missing"); continue
        add(f, scan_js(p.read_text(encoding="utf-8", errors="replace")))

    words = sum(len(t.split()) for t in inv)
    high = {t: e for t, e in inv.items() if any(not k.startswith("js-literal") for k in e["kinds"])}
    cand = len(inv) - len(high)
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

    OUT.mkdir(exist_ok=True)
    payload = {
        "generated": now,
        "scope": HTML_FILES + JS_FILES,
        "excluded": {"trip_essentials.js": "generated -- localise at build_trip_essentials.py"},
        "totals": {"unique_strings": len(inv), "high_confidence": len(high),
                   "js_literal_candidates": cand, "words": words},
        "per_file": per_file,
        "strings": [{"text": t, "kinds": sorted(e["kinds"]), "count": e["count"],
                     "locations": e["locations"]} for t, e in sorted(inv.items())],
    }
    (OUT / "inventory.json").write_text(json.dumps(payload, indent=1, ensure_ascii=False), encoding="utf-8")

    trend = OUT / "inventory_trend.csv"
    new = not trend.exists()
    with trend.open("a", newline="", encoding="utf-8") as fh:
        wcsv = csv.writer(fh)
        if new:
            wcsv.writerow(["run", "unique_strings", "high_confidence", "js_literal_candidates", "words"])
        wcsv.writerow([now, len(inv), len(high), cand, words])

    print(f"i18n inventory: {len(inv)} unique strings "
          f"({len(high)} high-confidence, {cand} js-literal candidates), {words} words")
    for f, c in per_file.items():
        print(f"  {f}: {c}")
    print(f"-> {OUT / 'inventory.json'}  (+ trend row)")

if __name__ == "__main__":
    sys.exit(main())
