#!/usr/bin/env python3
"""sync_quick_roles.py -- roles/role_registry.json -> the QUICK-ROLES data block in quick.html,
plus the 300x300 door-size role pictures in assets/quick_ph/role_<key>.jpg (pushed to
/static/quick by media_push.bat [1d], like every other Quick photo).

The registry is the one source (RUL-154/159); quick.html carries only a generated copy between
/* QUICK-ROLES:BEGIN */ and /* QUICK-ROLES:END */. Never hand-edit that block -- re-run this.
"""
import io, json, os, re, sys
from PIL import Image
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REG = os.path.join(ROOT, "roles", "role_registry.json")
QH = os.path.join(ROOT, "quick.html")
PH = os.path.join(ROOT, "assets", "quick_ph")
CHECK_ONLY = False   # set from argv at the bottom (SYNC-GUARD-1)

# door groups: the slate's working groups, in the words a worker would recognise
GROUP_LABEL = {
 "Home & care": "Home & care", "Food & hospitality": "Food & hospitality",
 "Retail & forecourt": "Shops & forecourt", "Logistics & yard": "Warehouse & delivery",
 "Site & general labour": "General & site work", "Trades-adjacent & informal": "Beauty, sewing & more",
 "Security": "Security", "Mining & heavy industry": "Heavy industry & plant",
 "Motor & transport": "Driving & vehicles", "Building trades": "Building trades",
 "Systems & installation": "Installers & repairs"}
MOVE = {"creche_assistant": "Home & care", "event_staff": "Food & hospitality",
        "car_washer": "Home & care"}  # CARWASH-1: area-bound like a cleaner, next to the cleaners  # display home
REP = {"Home & care": "home_cleaner", "Food & hospitality": "chef", "Shops & forecourt": "petrol_attendant",
 "Warehouse & delivery": "picker_packer", "General & site work": "builders_assistant",
 "Beauty, sewing & more": "hair_braider", "Security": "security_guard",
 "Heavy industry & plant": "welder", "Driving & vehicles": "code_10_code_14_driver",
 "Building trades": "bricklayer", "Installers & repairs": "solar_pv_installer"}

TRN_REP = {"Fitness & gym": "personal_trainer", "Combat sports": "boxing_coach", "Team sports": "soccer_coach",
 "Racket & target sports": "tennis_coach", "Water sports": "swimming_coach", "Running, cycling & outdoor": "running_athletics_coach",
 "Gymnastics & acrobatics": "gymnastics_coach", "Mind sports": "chess_coach"}

def main():
    reg = json.load(io.open(REG, encoding="utf-8"))
    roles, groups = [], []
    trn = []   # TRAINERS-DOOR-1 (RUL-217): the Tutors door's own roles -- kept OUT of SVC_ROLES (a Services role list)
    for r in reg["roles"]:
        if r["status"] != "in": continue
        if r.get("service_class") == "Trainers":
            trn.append(r)
            src = os.path.join(ROOT, r["role_picture"]["file"])
            dst = os.path.join(PH, "role_%s.jpg" % r["key"])
            if not os.path.exists(dst) or os.path.getmtime(dst) < os.path.getmtime(src):
                Image.open(src).convert("RGB").resize((300, 300), Image.LANCZOS).save(dst, "JPEG", quality=82)
            continue
        g = MOVE.get(r["key"]) or GROUP_LABEL[r["group"]]
        if g not in groups: groups.append(g)
        roles.append({"k": r["key"], "l": r["label"]["en"], "c": "C" if r["service_class"] == "Casuals" else "T",
                      "g": g, "f": r.get("finish_questions") or [], "gate": (r.get("gate") or {}).get("type")})
        src = os.path.join(ROOT, r["role_picture"]["file"])
        dst = os.path.join(PH, "role_%s.jpg" % r["key"])
        if not os.path.exists(dst) or os.path.getmtime(dst) < os.path.getmtime(src):
            Image.open(src).convert("RGB").resize((300, 300), Image.LANCZOS).save(dst, "JPEG", quality=82)
    grp = [{"g": g, "rep": REP[g]} for g in groups]
    block = ("/* QUICK-ROLES:BEGIN -- generated by scripts/sync_quick_roles.py from roles/role_registry.json; do not edit */\n"
             "var SVC_ROLES = %s;\nvar SVC_GROUPS = %s;\n/* QUICK-ROLES:END */"
             % (json.dumps(roles, ensure_ascii=False), json.dumps(grp, ensure_ascii=False)))
    q = io.open(QH, encoding="utf-8").read()
    pat = re.compile(r"/\* QUICK-ROLES:BEGIN.*?/\* QUICK-ROLES:END \*/", re.S)
    if not pat.search(q): sys.exit("quick.html has no QUICK-ROLES markers -- the SVC block is not installed")
    new = pat.sub(lambda m: block, q)
    # TRAINERS-DOOR-1 (RUL-217): TRN_ROLES / TRN_GROUPS, the Trainers door inside Tutors
    tgroups = []
    for r in trn:
        if r["group"] not in tgroups: tgroups.append(r["group"])
    tblock = ("/* QUICK-TRAINERS:BEGIN -- generated by scripts/sync_quick_roles.py from roles/role_registry.json; do not edit */\n"
              "var TRN_ROLES = %s;\nvar TRN_GROUPS = %s;\n/* QUICK-TRAINERS:END */"
              % (json.dumps([{"k": r["key"], "l": r["label"]["en"], "g": r["group"], "a": r.get("aliases") or [],
                              "gate": (r.get("gate") or {}).get("type")} for r in trn], ensure_ascii=False),
                 json.dumps([{"g": g, "rep": TRN_REP[g]} for g in tgroups], ensure_ascii=False)))
    tpat = re.compile(r"/\* QUICK-TRAINERS:BEGIN.*?/\* QUICK-TRAINERS:END \*/", re.S)
    if tpat.search(new): new = tpat.sub(lambda m: tblock, new)
    else: new = new.replace("/* QUICK-ROLES:END */", "/* QUICK-ROLES:END */\n" + tblock, 1)
    if CHECK_ONLY and _blockwise(q, tpat).strip() != tblock.strip():
        print("DRIFT: the QUICK-TRAINERS block in quick.html is not what role_registry.json generates -- run this script.")
    # the Quick door's words (preview) -- roles/quick_i18n.json is the one source
    src = json.load(io.open(os.path.join(ROOT, "roles", "quick_i18n.json"), encoding="utf-8"))
    L = src["langs"]
    d = {"w": {en: dict(zip(L, v)) for en, v in src["w"].items()},
         "p": [dict(zip(["en"] + L, x)) for x in src["p"]],
         "r": [dict(zip(["en"] + L, x)) for x in src["r"]]}
    ib = ("/* QUICK-I18N:BEGIN -- generated by scripts/sync_quick_roles.py from roles/quick_i18n.json; do not edit */\n"
          "var QI18N = %s;\n/* QUICK-I18N:END */" % json.dumps(d, ensure_ascii=False))
    ipat = re.compile(r"/\* QUICK-I18N:BEGIN.*?/\* QUICK-I18N:END \*/", re.S)
    if ipat.search(new): new = ipat.sub(lambda m: ib, new)
    if CHECK_ONLY:
        return _report_drift(q, block, ib, pat, ipat)
    if new != q: io.open(QH, "w", encoding="utf-8").write(new)
    print("quick.html: %d roles in %d groups; pictures in assets/quick_ph (role_*.jpg)" % (len(roles), len(grp)))
    print("quick.html: %d trainer roles in %d groups (TRAINERS-DOOR-1)" % (len(trn), len(tgroups)))
    return 0


def _blockwise(text, pat):
    m = pat.search(text)
    return m.group(0) if m else ""


def _qi18n_obj(text):
    """The QI18N object out of a quick.html, parsed. Returns None if it is not there or not
    parseable -- callers must treat that as NOT MEASURED, never as agreement."""
    m = re.search(r"var QI18N = (\{.*?\});", text, re.S)
    if not m:
        return None
    try:
        return json.loads(m.group(1))
    except Exception:
        return None


def _report_drift(q, block, ib, pat, ipat):
    """SYNC-CHECK-1 (27 Sep 2026) -- is the generated content in quick.html in step with its
    sources, JUDGED BY CONTENT AND NOT BY BYTES?

    Why this exists. Regression-ledger entry RG-0501 (QUICK-LANG-FULL-1) guarantees that every
    word on Quick's screens exists in isiZulu, isiXhosa, Sepedi and Afrikaans. On 27 Sep its board
    printed REGRESSION -- "quick.html's QI18N block is not the one roles/quick_i18n.json
    generates -- run scripts/sync_quick_roles.py" -- and rc=1, "Do not deploy over this", over a
    healthy page. MEASURED: regenerating the block changed 1 line and **0 keys and 0
    translations** (771 whole-sentence keys, 6 phrases, 34 patterns, identical before and after,
    value-for-value). The only difference was the ORDER the keys serialise in. So the conviction
    was a byte comparison wearing a language-gap's words -- the same class as RG-0028 and
    RG-0391, and the third time an instrument here has printed "do not deploy" over a healthy
    site.

    A missing key, a changed translation or a stale value still fails here. Serialisation order
    does not, because a reader cannot see it.
    """
    ok = True
    have_roles = _blockwise(q, pat)
    if have_roles.strip() != block.strip():
        print("DRIFT: the QUICK-ROLES block in quick.html is not what role_registry.json "
              "generates -- run this script with no arguments to regenerate it.")
        ok = False
    else:
        print("in step: QUICK-ROLES block matches roles/role_registry.json")

    want = _qi18n_obj(ib)
    have = _qi18n_obj(q)
    if want is None or have is None:
        print("NOT MEASURED: could not parse the QI18N object out of %s -- this is the checker "
              "being blind, not agreement." % ("the generated block" if want is None else "quick.html"))
        return 2
    canon = lambda d: json.dumps(d, sort_keys=True, ensure_ascii=False)
    if canon(want) == canon(have):
        print("in step: QI18N matches roles/quick_i18n.json -- %d words, %d phrases, %d patterns "
              "(compared by CONTENT; key order is not a fault a reader can see)"
              % (len(have.get("w", {})), len(have.get("p", [])), len(have.get("r", []))))
    else:
        ok = False
        hw, ww = have.get("w", {}), want.get("w", {})
        missing = sorted(set(ww) - set(hw))
        extra = sorted(set(hw) - set(ww))
        changed = [k for k in set(hw) & set(ww) if hw[k] != ww[k]]
        print("DRIFT: QI18N in quick.html is not the CONTENT roles/quick_i18n.json generates.")
        print("  missing from quick.html: %d%s" % (len(missing), (" e.g. " + repr(missing[0][:70])) if missing else ""))
        print("  present only in quick.html: %d%s" % (len(extra), (" e.g. " + repr(extra[0][:70])) if extra else ""))
        print("  same key, different translations: %d%s" % (len(changed), (" e.g. " + repr(changed[0][:70])) if changed else ""))
        if not (missing or extra or changed):
            print("  ...and none of the three: the phrase or pattern LISTS differ (p: %d vs %d, "
                  "r: %d vs %d). Still content, still worth fixing."
                  % (len(have.get("p", [])), len(want.get("p", [])),
                     len(have.get("r", [])), len(want.get("r", []))))
    return 0 if ok else 1


USAGE = """sync_quick_roles.py -- regenerate the generated blocks in quick.html from their sources.

  (no arguments)   regenerate QUICK-ROLES (from roles/role_registry.json) and QUICK-I18N
                   (from roles/quick_i18n.json) in quick.html, and WRITE the file.
  --check          report whether those blocks are in step, BY CONTENT, and write nothing.
                   exit 0 in step, 1 real drift, 2 could not measure.
  --help, -h       this text. Writes nothing.

SYNC-GUARD-1 (27 Sep 2026): this script used to ignore argv entirely, so `--help` RAN THE FULL
SYNC and rewrote a live page -- which is how the 27 Sep stand-up rewrote quick.html's 771-key
QI18N block while asking the script what it did. An informational call must never write."""

if __name__ == "__main__":
    _args = [a for a in sys.argv[1:] if a.strip()]
    CHECK_ONLY = "--check" in _args
    if "--help" in _args or "-h" in _args:
        print(USAGE)
        sys.exit(0)
    _unknown = [a for a in _args if a not in ("--check",)]
    if _unknown:
        sys.exit("unknown argument(s): %s\n\n%s" % (" ".join(_unknown), USAGE))
    sys.exit(main() or 0)
