#!/usr/bin/env python3
"""sync_quick_roles.py -- roles/role_registry.json -> the QUICK-ROLES data block in quick.html,
plus the 300x300 door-size role pictures in assets/quick_ph/role_<key>.jpg (pushed to
/static/quick by media_push.bat [1d], like every other Quick photo).

The registry is the one source (RUL-154/159); quick.html carries only a generated copy between
/* QUICK-ROLES:BEGIN */ and /* QUICK-ROLES:END */. Never hand-edit that block -- re-run this.
"""
import io, json, os, re, sys
from PIL import Image
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REG = os.path.join(ROOT, "roles", "role_registry.json")
QH = os.path.join(ROOT, "quick.html")
PH = os.path.join(ROOT, "assets", "quick_ph")

# door groups: the slate's working groups, in the words a worker would recognise
GROUP_LABEL = {
 "Home & care": "Home & care", "Food & hospitality": "Food & hospitality",
 "Retail & forecourt": "Shops & forecourt", "Logistics & yard": "Warehouse & delivery",
 "Site & general labour": "General & site work", "Trades-adjacent & informal": "Beauty, sewing & more",
 "Security": "Security", "Mining & heavy industry": "Heavy industry & plant",
 "Motor & transport": "Driving & vehicles", "Building trades": "Building trades",
 "Systems & installation": "Installers & repairs"}
MOVE = {"creche_assistant": "Home & care", "event_staff": "Food & hospitality"}  # display home
REP = {"Home & care": "home_cleaner", "Food & hospitality": "chef", "Shops & forecourt": "petrol_attendant",
 "Warehouse & delivery": "picker_packer", "General & site work": "builders_assistant",
 "Beauty, sewing & more": "hair_braider", "Security": "security_guard",
 "Heavy industry & plant": "welder", "Driving & vehicles": "code_10_code_14_driver",
 "Building trades": "bricklayer", "Installers & repairs": "solar_pv_installer"}

def main():
    reg = json.load(io.open(REG, encoding="utf-8"))
    roles, groups = [], []
    for r in reg["roles"]:
        if r["status"] != "in": continue
        g = MOVE.get(r["key"]) or GROUP_LABEL[r["group"]]
        if g not in groups: groups.append(g)
        roles.append({"k": r["key"], "l": r["label"]["en"], "c": "C" if r["service_class"] == "Casuals" else "T",
                      "g": g, "f": r.get("finish_questions") or [], "gate": (r.get("gate") or {}).get("type")})
        src = os.path.join(ROOT, r["role_picture"]["file"])
        dst = os.path.join(PH, "role_%s.jpg" % r["key"])
        if not os.path.exists(dst) or os.path.getmtime(dst) < os.path.getmtime(src):
            Image.open(src).convert("RGB").resize((300, 300), Image.LANCZOS).save(dst, "JPEG", quality=82)
    grp = [{"g": g, "rep": REP[g]} for g in groups]
    block = ("/* QUICK-ROLES:BEGIN -- generated by scripts/sync_quick_roles.py from roles/role_registry.json; do not edit */\n"
             "var SVC_ROLES = %s;\nvar SVC_GROUPS = %s;\n/* QUICK-ROLES:END */"
             % (json.dumps(roles, ensure_ascii=False), json.dumps(grp, ensure_ascii=False)))
    q = io.open(QH, encoding="utf-8").read()
    pat = re.compile(r"/\* QUICK-ROLES:BEGIN.*?/\* QUICK-ROLES:END \*/", re.S)
    if not pat.search(q): sys.exit("quick.html has no QUICK-ROLES markers -- the SVC block is not installed")
    new = pat.sub(lambda m: block, q)
    # the Quick door's words (preview) -- roles/quick_i18n.json is the one source
    src = json.load(io.open(os.path.join(ROOT, "roles", "quick_i18n.json"), encoding="utf-8"))
    L = src["langs"]
    d = {"w": {en: dict(zip(L, v)) for en, v in src["w"].items()},
         "p": [dict(zip(["en"] + L, x)) for x in src["p"]],
         "r": [dict(zip(["en"] + L, x)) for x in src["r"]]}
    ib = ("/* QUICK-I18N:BEGIN -- generated by scripts/sync_quick_roles.py from roles/quick_i18n.json; do not edit */\n"
          "var QI18N = %s;\n/* QUICK-I18N:END */" % json.dumps(d, ensure_ascii=False))
    ipat = re.compile(r"/\* QUICK-I18N:BEGIN.*?/\* QUICK-I18N:END \*/", re.S)
    if ipat.search(new): new = ipat.sub(lambda m: ib, new)
    if new != q: io.open(QH, "w", encoding="utf-8").write(new)
    print("quick.html: %d roles in %d groups; pictures in assets/quick_ph (role_*.jpg)" % (len(roles), len(grp)))

if __name__ == "__main__":
    main()
